ServerEvents.recipes(event => {

	// Large Dehydration Unit

    event.shaped('gtceu:large_dehydration_unit', [
            'ABA', 
            'CDC',
            'AEA'  
          ], {
            A: '#gtceu:circuits/iv', 
            B: 'gtceu:ev_electric_pump',  
            C: 'gtceu:rtm_alloy_coil_block',
			D: 'gtceu:clean_machine_casing',
			E: 'gtceu:ev_fluid_regulator'
          }
		  )

	// Large Evaporation Pool

	event.shaped('gtceu:large_evaporation_pool', [
            'ABA', 
            'CDC',
            'ABA'  
          ], {
            A: '#gtceu:circuits/iv', 
            B: 'gtceu:iv_electric_pump',  
            C: 'gtceu:rtm_alloy_coil_block',
			D: 'gtceu:iv_machine_casing',
          }
		  )

	// Radiation Chamber

	event.recipes.gtceu.assembler('atomic_alloy_plated_glass_package')
		.itemInputs('2x gtceu:fusion_glass','4x gtceu:atomic_alloy_plate')
  		.inputFluids('gtceu:plasticizer 576')
  		.itemOutputs('2x kubejs:atomic_alloy_plated_glass')
		.duration(200)
  		.EUt((GTValues.VA[GTValues.UV]))
		
	event.recipes.gtceu.assembly_line('radiation_chamber')
		.itemInputs('7x gtceu:dense_atomic_alloy_plate', '7x gtceu:dense_atomic_alloy_plate',  '4x gtceu:uv_electric_pump', '4x gtceu:uv_robot_arm', '8x #gtceu:circuits/uv', '16x gtceu:uv_autoclave')
		.itemOutputs('gtceu:xl_radiation_chamber')
		.inputFluids(
			Fluid.of('gtceu:polybenzimidazole', 32000),
			Fluid.of('gtceu:neoprene', 2304),
			Fluid.of('gtceu:soldering_alloy', 1152))
		.duration(20*100)
  		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.radiation_chamber('reinforced_epoxy_crosslinking_carbon_fibers')
		.itemInputs('2x gtceu:carbon_fibers')
		.inputFluids('gtceu:epoxy 288')
		.notConsumable('gtceu:plate_casting_mold')
		.chancedInput('4x gtceu:naquadria_bolt', 2500, 0)
		.itemOutputs('3x gtceu:reinforced_epoxy_resin_plate')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.radiation_chamber('reinforced_epoxy_crosslinking_carbon_nanotubes')
		.itemInputs('2x gtceu:fine_carbon_nanotubes_wire')
		.inputFluids('gtceu:epoxy 288')
		.notConsumable('gtceu:plate_casting_mold')
		.chancedInput('4x gtceu:resonant_naquadah_bolt', 2500, 0)
		.itemOutputs('4x gtceu:reinforced_epoxy_resin_plate')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UV]))
	
	event.recipes.gtceu.radiation_chamber('reinforced_epoxy_crosslinking_kevlar_fibers')
		.itemInputs('2x kubejs:kevlar_fibers')
		.inputFluids('gtceu:epoxy 288')
		.notConsumable('gtceu:plate_casting_mold')
		.chancedInput('4x gtceu:hypoxylon_bolt', 2500, 0)
		.itemOutputs('6x gtceu:reinforced_epoxy_resin_plate')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UHV]))
		
	// Polymerization Chamber

	event.recipes.gtceu.assembler('peek_reinforced_glass_package')
		.itemInputs('2x gtceu:laminated_glass','6x gtceu:peek_plate')
  		.inputFluids('gtceu:plasticizer 576')
  		.itemOutputs('2x kubejs:peek_reinforced_glass')
		.duration(20*10)
  		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.assembler('machine_casing_inert_peek')
		.itemInputs('gtceu:inert_machine_casing')
  		.inputFluids('gtceu:peek 216')
		.circuit(6)
  		.itemOutputs('kubejs:machine_casing_inert_peek')
		.duration(20*5)
  		.EUt((GTValues.VA[GTValues.LV]))
	
	event.recipes.gtceu.assembler('peek_plated_heat_resisted_casing')
		.itemInputs('4x gtceu:titanium_carbide_plate', '2x gtceu:kaemite_plate', 'gtceu:peek_frame')
  		.inputFluids('gtceu:peek 216')
		.circuit(6)
  		.itemOutputs('2x kubejs:peek_plated_heat_resisted_casing')
		.duration(20*5)
  		.EUt((GTValues.VA[GTValues.LV]))
	
	event.shaped(
        '2x kubejs:machine_casing_pipe_peek',
        ['ABA', 'BYB', 'ABA'],
        {
            A: 'gtceu:peek_plate',
            B: 'gtceu:peek_normal_fluid_pipe',
            Y: 'gtceu:peek_frame',
    })

	event.recipes.gtceu.assembly_line('large_polymerization_chamber')
		.itemInputs('16x gtceu:chemical_plant', '16x gtceu:large_dehydration_unit', '16x gtceu:large_solidifier', '16x gtceu:uhv_electric_pump', '8x gtceu:uhv_robot_arm', '16x #gtceu:circuits/uev', '16x gtceu:peek_plate', '16x avaritia:neutron_gear', '64x gtceu:fine_kaemite_wire', '64x gtceu:fine_kaemite_wire', '64x gtceu:antimatter_foil', '64x gtceu:antimatter_foil', '64x gtceu:resonant_essence_screw')
		.itemOutputs('gtceu:large_polymerization_chamber')
		.inputFluids(
			Fluid.of('gtceu:peek', 32000),
			Fluid.of('gtceu:neoprene', 2304),
			Fluid.of('gtceu:soldering_alloy', 1152)
		)
		.duration(20*100)
  		.EUt((GTValues.VA[GTValues.UEV]))

	// Better Polymerilization/Vulcanization

	event.recipes.gtceu.large_chemical_reactor('triethylaluminium')
		.inputFluids('gtceu:hydrogen 6000', "gtceu:ethylene 6000")
		.circuit(3)
		.itemInputs('1x gtceu:aluminium_dust')
  		.outputFluids("gtceu:triethylaluminium 2000")
  		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UV]))
		
	event.recipes.gtceu.chemical_reactor('carbon_sulfide')
		.inputFluids('gtceu:methane 2000')
		.notConsumable("gtceu:silicon_dioxide_dust")
		.itemInputs('8x gtceu:sulfur_dust')
  		.outputFluids("gtceu:carbon_sulfide 2000", "gtceu:hydrogen_sulfide 4000")
  		.duration(20*40)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.chemical_reactor('sodium_dimethyldithiocarbamate')
		.inputFluids("gtceu:dimethylamine 2000", "gtceu:carbon_sulfide 1000")
		.itemInputs('3x gtceu:sodium_hydroxide_dust')
  		.outputFluids("minecraft:water 1000")
		.itemOutputs('5x gtceu:sodium_dimethyldithiocarbamate_dust')
  		.duration(20*55)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.large_chemical_reactor('tetramethylthiuramdisulfide')
		.inputFluids("gtceu:hydrogen_peroxide 1000")
		.itemInputs('10x gtceu:sodium_dimethyldithiocarbamate_dust')
		.itemOutputs('5x gtceu:tetramethylthiuramdisulfide_dust', '6x gtceu:sodium_hydroxide_dust')
  		.duration(20*25)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.mixer('tetramethylthiuramdisulfide')
		.inputFluids("minecraft:water 1000")
		.itemInputs('10x gtceu:tetramethylthiuramdisulfide_dust')
		.outputFluids("gtceu:tetramethylthiuramdisulfide_solution 1500")
  		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.extractor('cocoa_oil_extraction')
		.itemInputs("gtceu:cocoa_dust")
		.outputFluids('gtceu:cocoa_oil 72')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.ULV]))

	event.recipes.gtceu.distillation_tower('cocoa_oil_distillation')
		.inputFluids("gtceu:cocoa_oil 1500")
		.itemOutputs('5x gtceu:stearic_acid_dust')
		.outputFluids("gtceu:biomass 500","gtceu:oleic_acid 500")
  		.duration(20*30)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.chemical_reactor('stearic_acid')
		.inputFluids("gtceu:oleic_acid 1000", "gtceu:hydrogen 2000")
		.itemOutputs('10x gtceu:stearic_acid_dust')
  		.duration(20*50)
		.EUt((GTValues.VA[GTValues.IV]))

	event.recipes.gtceu.polymerization_chamber('better_polyvinyl_chloride')
		.inputFluids("gtceu:vinyl_chloride 2106")
		.circuit(2)
		.perTick(true)
        .inputFluids("gtceu:titanium_tetrachloride 10", "gtceu:triethylaluminium 15", "gtceu:liquid_oxygen 50")
        .perTick(false)
		.outputFluids("gtceu:polyvinyl_chloride 6318")
		.duration(20*20*5)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.polymerization_chamber('better_polyethylene')
		.inputFluids("gtceu:ethylene 2106")
		.circuit(2)
		.perTick(true)
        .inputFluids("gtceu:titanium_tetrachloride 10", "gtceu:triethylaluminium 15", "gtceu:liquid_oxygen 50")
        .perTick(false)
		.outputFluids("gtceu:polyethylene 6318")
		.duration(20*20*5)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.polymerization_chamber('better_polytetrafluoroethylene')
		.inputFluids("gtceu:tetrafluoroethylene 2106")
		.circuit(2)
		.perTick(true)
        .inputFluids("gtceu:titanium_tetrachloride 10", "gtceu:triethylaluminium 15", "gtceu:liquid_oxygen 50")
        .perTick(false)
		.outputFluids("gtceu:polytetrafluoroethylene 6318")
		.duration(20*20*5)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.polymerization_chamber('better_polyvinyl_acetate')
		.inputFluids("gtceu:vinyl_acetate 2106")
		.circuit(2)
		.perTick(true)
        .inputFluids("gtceu:titanium_tetrachloride 10", "gtceu:triethylaluminium 15", "gtceu:liquid_oxygen 50")
        .perTick(false)
		.outputFluids("gtceu:polyvinyl_acetate 6318")
		.duration(20*20*5)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.polymerization_chamber('better_rubber')
		.itemInputs("1x gtceu:zincite_dust", "9x gtceu:raw_rubber_dust", "3x gtceu:stearic_acid_dust")
		.perTick(true)
        .inputFluids("gtceu:tetramethylthiuramdisulfide_solution 10")
        .perTick(false)
		.outputFluids("gtceu:rubber 2592")
		.duration(20*10*5)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.polymerization_chamber('better_styrene_butadiene_rubber')
		.itemInputs("1x gtceu:zincite_dust", "9x gtceu:raw_styrene_butadiene_rubber_dust", "3x gtceu:stearic_acid_dust")
		.perTick(true) 
        .inputFluids("gtceu:tetramethylthiuramdisulfide_solution 10")
        .perTick(false)
		.outputFluids("gtceu:styrene_butadiene_rubber 2592")
		.duration(20*10*5)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.polymerization_chamber('better_silicone_rubber')
		.itemInputs("1x gtceu:zincite_dust", "9x gtceu:polydimethylsiloxane_dust", "3x gtceu:stearic_acid_dust")
		.perTick(true) 
        .inputFluids("gtceu:tetramethylthiuramdisulfide_solution 10")
        .perTick(false)
		.outputFluids("gtceu:silicone_rubber 2592")
		.duration(20*10*5)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.polymerization_chamber('better_neoprene')
		.itemInputs("1x gtceu:zincite_dust", "9x gtceu:raw_neoprene_dust", "3x gtceu:stearic_acid_dust")
		.perTick(true) 
        .inputFluids("gtceu:tetramethylthiuramdisulfide_solution 10")
        .perTick(false)
		.outputFluids("gtceu:neoprene 2592")
		.duration(20*10*5)
		.EUt((GTValues.VA[GTValues.UEV]))

	// High-Pressure Reactor

	event.recipes.gtceu.assembler('ultimate_engine_intake_casing')
		.itemInputs('4x gtceu:neutronium_normal_fluid_pipe', '1x kubejs:neutronium_casing', '16x gtceu:neutronium_turbine_blade', '2x gtceu:neutronium_gear')
  		.itemOutputs('2x kubejs:ultimate_engine_intake_casing')
		.duration(20*5)
  		.EUt((GTValues.VA[GTValues.LV]))

	event.recipes.gtceu.assembly_line('large_high_pressure_reactor')
		.itemInputs('16x gtceu:chemical_plant', "16x gtceu:atomicompressor", '16x gtceu:atmospheric_collector', '16x gtceu:uiv_electric_pump', '8x gtceu:uiv_electric_piston', '16x #gtceu:circuits/uiv', '16x kubejs:chaos_heavy_plating', '16x gtceu:awakened_draconium_gear', '64x gtceu:fine_cosmic_osmium_wire', '64x gtceu:fine_cosmic_osmium_wire', '64x gtceu:heavy_duty_alloy_t4_foil', '64x gtceu:heavy_duty_alloy_t4_foil', '64x gtceu:cosmic_tungsten_screw')
		.itemOutputs('gtceu:large_high_pressure_reactor')
		.inputFluids(
			Fluid.of('gtceu:peek', 32000),
			Fluid.of('gtceu:neoprene', 2304),
			Fluid.of('gtceu:soldering_alloy', 1152),
			Fluid.of("gtceu:astral_flux_plasma", 5000)
		)
		.duration(20*150)
  		.EUt((GTValues.VA[GTValues.UXV]))

	// Catalysts and byproducts
	
	event.recipes.gtceu.large_chemical_reactor('sodium_acetate')
		.inputFluids('gtceu:hydrochloric_acid 1000')
		.itemInputs('1x gtceu:sodium_acetate_dust')
  		.outputFluids("gtceu:acetic_acid 1000")
		.itemOutputs('1x gtceu:salt_dust')
  		.duration(20*5)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.chemical_reactor('cuprous_chloride')
		.itemInputs('2x gtceu:copper_dust')
		.inputFluids('gtceu:chlorine 2000')
		.itemOutputs('2x gtceu:cuprous_chloride_dust')
		.duration(20*5)
		.EUt((GTValues.VA[GTValues.MV]))

	event.recipes.gtceu.chemical_reactor('antimony_pentafluoride')
		.itemInputs('4x gtceu:antimony_trifluoride_dust')
		.inputFluids('gtceu:fluorine 4000')
		.itemOutputs('2x gtceu:antimony_pentafluoride_dust')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.IV]))
	
	event.recipes.gtceu.chemical_reactor('aluminium_chloride')
		.itemInputs('2x gtceu:aluminium_dust')
		.inputFluids('gtceu:chlorine 6000')
		.itemOutputs('8x gtceu:aluminium_chloride_dust')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.chemical_reactor('iron_sulfate')
		.itemInputs('1x gtceu:iron_dust')
		.inputFluids('gtceu:sulfuric_acid 1000')
		.itemOutputs('6x gtceu:iron_sulfate_dust')
		.outputFluids("gtceu:hydrogen 1000")
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.chemical_reactor('alumina')
		.itemInputs('2x gtceu:aluminium_dust')
		.inputFluids('gtceu:oxygen 3000')
		.itemOutputs('5x gtceu:alumina_dust')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.MV]))

	event.recipes.gtceu.large_chemical_reactor('cobalt_alumina_catalyst')
		.itemInputs('2x gtceu:alumina_dust', "3x gtceu:cobalt_oxide_dust")
		.notConsumable("gtceu:platinum_dust")
		.itemOutputs('5x gtceu:cobalt_alumina_catalyst_dust')
		.duration(20*32)
		.EUt((GTValues.VA[GTValues.LuV]))
			
	event.recipes.gtceu.chemical_reactor('activated_cobalt_alumina_catalyst')
		.itemInputs('5x gtceu:cobalt_alumina_catalyst_dust')
		.inputFluids('gtceu:hydrogen 2000')
		.itemOutputs('2x gtceu:activated_cobalt_alumina_catalyst_dust')
		.outputFluids("minecraft:water 1000")
		.duration(20*16)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.chemical_reactor('manganese_sulfate')
		.itemInputs('3x gtceu:pyrolusite_dust')
		.inputFluids('gtceu:sulfuric_acid 2000')
		.itemOutputs('6x gtceu:manganese_sulfate_dust')
		.outputFluids("minecraft:water 2000")
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.chemical_reactor('manganese_carbonate')
		.itemInputs('6x gtceu:manganese_sulfate_dust', "4x gtceu:soda_ash_dust")
		.itemOutputs('5x gtceu:manganese_carbonate_dust')
		.duration(20*200)
		.EUt((GTValues.VA[GTValues.HV]))
	
	event.recipes.gtceu.chemical_reactor('manganese_acetate')
		.itemInputs('5x gtceu:manganese_carbonate_dust')
		.inputFluids('gtceu:acetic_acid 2000')
		.itemOutputs('19x gtceu:manganese_acetate_dust')
		.outputFluids("minecraft:water 1000", "gtceu:carbon_dioxide 1000")
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.large_chemical_reactor('nickel_bromide')
		.itemInputs('5x gtceu:nickel_dust', '2x gtceu:boron_dust')
		.notConsumable("gtceu:platinum_dust")
		.itemOutputs('7x gtceu:nickel_bromide_dust')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.chemical_reactor('sodium_cyanide')
		.itemInputs('3x gtceu:sodium_hydroxide_dust')
		.inputFluids("gtceu:hydrogen_cyanide 1000")
		.outputFluids("minecraft:water 1000")
		.itemOutputs('3x gtceu:sodium_cyanide_dust')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.chemical_reactor('hydrazine_sulfate')
		.inputFluids("gtceu:dinitrogen_tetroxide 1000", "gtceu:sulfuric_acid 1000")
		.itemOutputs('13x gtceu:hydrazine_sulfate_dust')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.IV]))

	event.recipes.gtceu.chemical_reactor('acetone_cyanohydrin')
		.itemInputs('3x gtceu:sodium_cyanide_dust', '13x gtceu:hydrazine_sulfate_dust')
		.inputFluids("gtceu:acetone 1000")
		.itemOutputs("7x gtceu:sodium_bisulfate_dust")
		.outputFluids("gtceu:acetone_cyanohydrin 1500", "gtceu:ammonia 1000")
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.IV]))

	event.recipes.gtceu.chemical_reactor('isobutyramide')
		.inputFluids("gtceu:acetone_cyanohydrin 1000", "gtceu:dinitrogen_tetroxide 1000")
		.outputFluids("gtceu:isobutyramide 1000", "minecraft:water 2000")
		.duration(20*23)
		.EUt((GTValues.VA[GTValues.IV]))
	
	event.recipes.gtceu.chemical_reactor('azo_isobutyronitrile')
		.inputFluids("gtceu:isobutyramide 1000", "gtceu:chlorine 2000")
		.outputFluids("gtceu:hydrochloric_acid 2000")
		.itemOutputs('6x gtceu:azo_isobutyronitrile_dust')
		.duration(20*41)
		.EUt((GTValues.VA[GTValues.LuV]))
		
	event.recipes.gtceu.chemical_reactor('barium_chloride')
		.inputFluids("gtceu:hydrochloric_acid 2000")
		.itemInputs("2x gtceu:barium_sulfide_dust")
		.outputFluids("gtceu:hydrogen_sulfide")
		.itemOutputs('3x gtceu:barium_chloride_dust')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.IV]))

	event.recipes.gtceu.chemical_reactor('potassium_manganate')
		.inputFluids("gtceu:oxygen 1000")
		.itemInputs("6x gtceu:pyrolusite_dust", "12x gtceu:potassium_hydroxide_dust")
		.outputFluids("minecraft:water 2000")
		.itemOutputs('14x gtceu:potassium_manganate_dust')
		.duration(20*45)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.chemical_reactor('barium_manganate')
		.inputFluids("minecraft:water 1000")
		.itemInputs("3x gtceu:barium_chloride_dust", "7x gtceu:potassium_manganate_dust")
		.itemOutputs('6x gtceu:barium_manganate_dust', "4x gtceu:rock_salt_dust")
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_reactor('barium_permanganate')
		.inputFluids("gtceu:sulfuric_acid 2000")
		.itemInputs("18x gtceu:barium_manganate_dust")
		.itemOutputs('11x gtceu:barium_permanganate_dust', "12x gtceu:barium_sulfate_dust", "3x gtceu:pyrolusite_dust")
		.outputFluids("minecraft:water 2000")
		.duration(20*45)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_reactor('cobalt_sulfate')
		.inputFluids("gtceu:sulfuric_acid 1000")
		.itemInputs("2x gtceu:cobalt_oxide_dust")
		.itemOutputs('6x gtceu:cobalt_sulfate_dust')
		.outputFluids("minecraft:water 1000")
		.duration(20*120)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.chemical_reactor('cobalt_permanganate_solution')
		.inputFluids("minecraft:water 1000")
		.itemInputs("2x gtceu:cobalt_oxide_dust", "11x gtceu:barium_permanganate_dust")
		.itemOutputs('6x gtceu:barium_sulfate_dust')
		.outputFluids("gtceu:cobalt_permanganate_solution 1000")
		.duration(20*210)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.centrifuge('cobalt_permanganate')
		.inputFluids("gtceu:cobalt_permanganate_solution 1000")
		.itemOutputs('11x gtceu:cobalt_permanganate_dust')
		.outputFluids("minecraft:water 1000")
		.duration(20*85)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.electrolyzer('copper_sulfate')
		.inputFluids("gtceu:sulfuric_acid 1000")
		.itemInputs("2x gtceu:copper_rod")
		.itemOutputs('6x gtceu:copper_sulfate_dust')
		.outputFluids("gtceu:hydrogen 2000")
		.duration(20*67)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_reactor('hydro_ammonia_copper_chromate')
		.inputFluids("minecraft:water 3000", "gtceu:ammonia 4000")
		.itemInputs("12x gtceu:copper_sulfate_dust", "7x gtceu:potassium_dichromate_dust")
		.itemOutputs('6x gtceu:hydro_ammonia_copper_chromate_dust', '7x gtceu:potassium_sulfate_dust', '15x gtceu:ammonium_sulfate_dust')
		.duration(20*150)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.dehydration_unit('copper_chromite')
		.itemInputs("6x gtceu:hydro_ammonia_copper_chromate_dust")
		.itemOutputs('9x gtceu:copper_chromite_dust')
		.outputFluids("minecraft:water 5000", "gtceu:nitrogen 2000")
		.duration(20*60*4)
		.EUt((GTValues.VA[GTValues.UEV]))


	// Silicone Rubber Rework	 
	
	event.recipes.gtceu.chemical_reactor('trichlorosilane_synthesis')
		.itemInputs('3x gtceu:silicon_dust')
		.inputFluids('gtceu:hydrochloric_acid 3000')
		.outputFluids('gtceu:trichlorosilane 2000', 'gtceu:hydrogen 500')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.MV]))

	event.recipes.gtceu.distillation_tower('purify_trichlorosilane')
		.inputFluids('gtceu:trichlorosilane 1000')
		.outputFluids('gtceu:pure_trichlorosilane 800', 'gtceu:diluted_hydrochloric_acid 200')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.large_chemical_reactor('dimethyldichlorosilane')
		.inputFluids('gtceu:pure_trichlorosilane 1000', 'gtceu:methane 2000')
		.notConsumable('gtceu:copper_dust') 
		.outputFluids('gtceu:dimethyldichlorosilane 1500', 'gtceu:hydrochloric_acid 500')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.HV]))
	 
	event.recipes.gtceu.large_chemical_reactor('silicone_prepolymer')
		.inputFluids('gtceu:dimethyldichlorosilane 1000', 'minecraft:water 2000')
		.outputFluids('gtceu:silicone_prepolymer 1500', 'gtceu:hydrochloric_acid 1000')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.dehydration_unit('silicone_vulcanization')
		.inputFluids('gtceu:silicone_prepolymer 1000', 'gtceu:methyl_acetate 500')
		.itemOutputs('3x gtceu:polydimethylsiloxane_dust')
		.duration(20*4*10)
		.EUt((GTValues.VA[GTValues.EV]))
	  
	// SBR Rework  

	event.recipes.gtceu.dehydration_unit('styrene_synth')
	 	.inputFluids('gtceu:ethylbenzene 1000')
  		.outputFluids('gtceu:styrene 750', 'gtceu:hydrogen 250')
	 	.duration(20*4*5)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.large_chemical_reactor('sbr_emulsion')
  		.inputFluids('gtceu:butadiene 750', 'gtceu:styrene 250', 'minecraft:water 1000')
  		.outputFluids('gtceu:sbr_emulsion 2000')
  		.duration(20*15)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.dehydration_unit('sbr_coagulation')
  		.inputFluids('gtceu:sbr_emulsion 2000')
		.notConsumable('gtceu:calcium_chloride_dust')
  		.itemOutputs('6x gtceu:raw_styrene_butadiene_rubber_dust')
  		.duration(4*20*10)
		.EUt((GTValues.VA[GTValues.EV]))

	// Laminated Glass Rework

	event.recipes.gtceu.dehydration_unit('plasticizer_synthesis')
  		.inputFluids('gtceu:butyraldehyde 1000', 'gtceu:ethanol 4000')
		.outputFluids('gtceu:plasticizer 1000', "minecraft:water 1000")
		.duration(20*10*4)
	  	.EUt((GTValues.VA[GTValues.MV]))

	event.recipes.gtceu.assembler('glass_lamination_package')
		.itemInputs('2x gtceu:tempered_glass','4x gtceu:polyvinyl_butyral_foil')
  		.inputFluids('gtceu:plasticizer 144')
  		.itemOutputs('1x gtceu:laminated_glass')
		.duration(200)
  		.EUt((GTValues.VA[GTValues.HV]))

	// Epoxy Rework

	event.recipes.gtceu.dehydration_unit('epichlorohydrin_allyl_chloride_way')
  		.inputFluids('gtceu:allyl_chloride 1000', 'gtceu:hypochlorous_acid 1000')
		.itemInputs('3x gtceu:sodium_hydroxide_dust')
		.outputFluids('gtceu:epichlorohydrin 1000', 'minecraft:water 1000')
		.itemOutputs('2x gtceu:salt_dust')
		.duration(20*10*2)
	  	.EUt((GTValues.VA[GTValues.HV]))
	
	event.recipes.gtceu.dehydration_unit('epichlorohydrin_glycerol_way')
  		.inputFluids('gtceu:glycerol 1000', 'gtceu:hydrochloric_acid 1000')
		.outputFluids('gtceu:epichlorohydrin 1000','minecraft:water 2000')
		.duration(15*10*2)
	  	.EUt((GTValues.VA[GTValues.HV]))
	
	event.recipes.gtceu.evaporation_pool('epoxy_pool')
  		.inputFluids('gtceu:epichlorohydrin 10000', 'gtceu:bisphenol_a 10000')
		.itemInputs('30x gtceu:sodium_hydroxide_dust')
		.itemOutputs('69x gtceu:epoxy_dust', '20x gtceu:salt_dust')
		.duration(20*100)
	  	.EUt((GTValues.VA[GTValues.EV]))

	// PBI Rework

	event.recipes.gtceu.large_chemical_reactor('hydrazobenzene')
  		.inputFluids("gtceu:nitrobenzene 2000")
		.notConsumable('gtceu:zinc_dust') 
		.itemInputs("2x gtceu:potassium_hydroxide_dust", "2x gtceu:carbon_dust")
  		.outputFluids('gtceu:hydrazobenzene 1000', "gtceu:carbon_monoxide 1000")
		.itemOutputs('6x gtceu:potassium_carbonate_dust')
  		.duration(20*15)
		.EUt((GTValues.VA[GTValues.HV]))
	
	event.recipes.gtceu.large_chemical_reactor('diacetyl_benzidine')
  		.inputFluids("gtceu:hydrazobenzene 1000", "gtceu:acetic_anhydride 2000")
  		.outputFluids('gtceu:diacetyl_benzidine 1000', "gtceu:acetic_acid 2000")
  		.duration(20*30)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.large_chemical_reactor('dinitro_diacetyl_benzidine')
  		.inputFluids("gtceu:diacetyl_benzidine 1000", "gtceu:nitric_acid 2000")
  		.outputFluids('gtceu:dinitro_diacetyl_benzidine 1000', "minecraft:water 2000")
  		.duration(20*5)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.large_chemical_reactor('dinitro_benzidine')
  		.inputFluids("gtceu:dinitro_diacetyl_benzidine 3000")
		.itemInputs('6x gtceu:sodium_hydroxide_dust')
  		.outputFluids('gtceu:dinitro_benzidine 3000')
		.itemOutputs('6x gtceu:sodium_acetate_dust')
  		.duration(20*7)
		.EUt((GTValues.VA[GTValues.IV]))
		
	event.recipes.gtceu.evaporation_pool('diaminobenzidine')
  		.inputFluids('gtceu:dinitro_benzidine 10000', "gtceu:hydrochloric_acid 120000")
		.itemInputs('60x gtceu:iron_dust')
		.outputFluids('gtceu:diaminobenzidine 10000', 'gtceu:iron_ii_chloride 60000')
		.duration(20*100)
	  	.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.evaporation_pool('phthalic_acid_from_dimethylbenzene')
  		.inputFluids('gtceu:dimethylbenzene 90000', "gtceu:oxygen 180000")
		.itemInputs('10x gtceu:potassium_dichromate_dust')
		.outputFluids('gtceu:phthalic_acid 90000')
		.duration(20*100)
	  	.EUt((GTValues.VA[GTValues.IV]))
	
	event.recipes.gtceu.evaporation_pool('phthalic_acid_from_naphthalene')
  		.inputFluids('gtceu:naphthalene 180000', "gtceu:sulfuric_acid 90000")
		.itemInputs('10x gtceu:potassium_dust')
		.outputFluids('gtceu:phthalic_acid 225000', 'gtceu:hydrogen_sulfide 90000')
		.duration(20*200)
	  	.EUt((GTValues.VA[GTValues.IV]))

	// Neoprene

	event.recipes.gtceu.chemical_reactor('calcium_carbide_production')
		.itemInputs('3x gtceu:quicklime_dust', '2x gtceu:coke_dust')
  		.itemOutputs('3x gtceu:calcium_carbide_dust')
		.outputFluids('gtceu:carbon_monoxide 1000')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.chemical_reactor('acetylene_generation')
		.itemInputs('3x gtceu:calcium_carbide_dust')
		.inputFluids('minecraft:water 2000')
		.outputFluids('gtceu:acetylene 1000')
		.itemOutputs('5x gtceu:calcium_hydroxide_dust')
		.duration(20*1)
		.EUt((GTValues.VA[GTValues.ZPM]))
	
	event.recipes.gtceu.dehydration_unit('vinylacetylene_synthesis')
		.inputFluids('gtceu:acetylene 2000')
		.notConsumable('gtceu:cuprous_chloride_dust') 
		.outputFluids('gtceu:vinylacetylene 750', 'gtceu:hydrogen 250')
		.duration(20*3*20)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.dehydration_unit('chloroprene_synthesis')
		.inputFluids('gtceu:vinylacetylene 1000', 'gtceu:hydrochloric_acid 1000')
		.notConsumable('gtceu:ammonium_chloride_dust')
		.outputFluids('gtceu:chloroprene 800', 'minecraft:water 200')
		.duration(20*3*5)
		.EUt((GTValues.VA[GTValues.LuV]))
	
	event.recipes.gtceu.large_chemical_reactor('neoprene_emulsion')
		.inputFluids('gtceu:chloroprene 1000', 'minecraft:water 2000', 'gtceu:sodium_persulfate 500')
		.outputFluids('gtceu:neoprene_latex 2500')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.evaporation_pool('neoprene_coagulation')
  		.inputFluids('gtceu:neoprene_latex 10000')
		.itemInputs('10x gtceu:calcium_chloride_dust')
  		.itemOutputs('60x gtceu:raw_neoprene_dust')
  		.duration(20*100)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.chemical_reactor('neoprene_vulcanization')
		.itemInputs('9x gtceu:raw_neoprene_dust', 'gtceu:sulfur_dust')
		.outputFluids('gtceu:neoprene 1296')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.LV]))

	event.recipes.gtceu.chemical_plant('chloroprene_shortcut')
		.notConsumable('kubejs:chemical_tier_three')
		.inputFluids("gtceu:hydrochloric_acid 1000", "gtceu:acetylene 2000")
		.outputFluids('gtceu:chloroprene 2500', "minecraft:water 1000")
		.duration(20*45)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.polymerization_chamber('neoprene_shortcut')
		.inputFluids('gtceu:chloroprene 1000', 'minecraft:water 1000')
		.itemInputs("3x gtceu:calcium_chloride_dust")
		.perTick(true)
        .inputFluids('gtceu:sodium_persulfate 5')
        .perTick(false)
		.itemOutputs('18x gtceu:raw_neoprene_dust')
		.duration(20*50*5)
		.EUt((GTValues.VA[GTValues.UHV]))
		
	// XLPE 

	event.recipes.gtceu.chemical_reactor('cumene_hydroperoxide')
		.inputFluids('gtceu:cumene 1000', 'gtceu:oxygen 2000')
		.notConsumable('gtceu:cobalt_oxide_dust')
		.outputFluids('gtceu:cumene_hydroperoxide 1000')
		.duration(20*8)
		.EUt((GTValues.VA[GTValues.LV]))
	
	event.recipes.gtceu.chemical_reactor('cumene_hydroperoxide_phenol_acetone')
		.inputFluids('gtceu:cumene_hydroperoxide 1000')
		.circuit(2)
		.outputFluids('gtceu:phenol 1000', 'gtceu:acetone 1000')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.LV]))

	event.recipes.gtceu.dehydration_unit('dicumyl_peroxide_synthesis')
		.inputFluids('gtceu:cumene_hydroperoxide 2000')
		.notConsumableFluid('gtceu:sulfuric_acid 1000')
		.outputFluids('gtceu:dicumyl_peroxide 1000', 'minecraft:water 1000')
		.duration(20*5*20)
		.EUt((GTValues.VA[GTValues.ZPM]))
	
	event.recipes.gtceu.mixer('pe_peroxide_mixing')
		.inputFluids('gtceu:polyethylene 1000', 'gtceu:dicumyl_peroxide 150')
		.outputFluids('gtceu:pe_peroxide_mixture 1150')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.autoclave('thermal_crosslinking')
		.inputFluids('gtceu:pe_peroxide_mixture 500')
		.notConsumable('gtceu:quantum_star')
		.notConsumable('gtceu:plate_casting_mold')
		.itemOutputs('3x gtceu:thermal_treated_xlpe_plate')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UV]))
	
	event.recipes.gtceu.radiation_chamber('radiation_crosslinking')
		.itemInputs('20x gtceu:thermal_treated_xlpe_plate')
		.inputFluids('gtceu:dicumyl_peroxide 50')
		.chancedInput('4x gtceu:naquadria_bolt', 2500, 0)
		.itemOutputs('19x gtceu:xlpe_plate')
		.duration(20*100)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_plant('xlpe_shortcut')
		.itemInputs('2x gtceu:naquadria_rod')
		.notConsumable('kubejs:chemical_tier_four')
		.inputFluids("gtceu:polyethylene 10000", 'gtceu:cumene 1000', 'gtceu:oxygen 2000')
		.outputFluids('gtceu:xlpe 7500')
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UEV]))

	// PEEK

	event.recipes.gtceu.dehydration_unit('fluorobenzene_synthesis')
		.inputFluids('gtceu:benzene 1000', 'gtceu:hydrofluoric_acid 500')
		.notConsumable('gtceu:antimony_pentafluoride_dust')
		.outputFluids('gtceu:fluorobenzene 1000', 'gtceu:hydrogen 500')
		.duration(20*5*30)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.evaporation_pool('phosgene_synthesis')
		.inputFluids('gtceu:chloroform 200000', 'gtceu:oxygen 200000')
		.outputFluids('gtceu:phosgene 200000', 'gtceu:hydrochloric_acid 200000')
		.duration(20*200)
		.EUt((GTValues.VA[GTValues.UV]))
		
	event.recipes.gtceu.chemical_reactor('difluorobenzophenone_synthesis')
		.inputFluids('gtceu:fluorobenzene 2000', 'gtceu:phosgene 1000')
		.notConsumable('gtceu:aluminium_chloride_dust')
		.outputFluids('gtceu:difluorobenzophenone 1000', 'gtceu:hydrochloric_acid 2000')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.dehydration_unit('difluorobenzophenone_purification')
		.inputFluids('gtceu:difluorobenzophenone 10000', 'gtceu:oxygen 2000')
		.itemOutputs('32x gtceu:purified_difluorobenzophenone_dust')
		.duration(20*25*6)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_reactor('thionyl_chloride_synthesis')
		.inputFluids('gtceu:phosgene 1000',"gtceu:sulfur_dioxide 1000")
		.outputFluids('gtceu:thionyl_chloride 1000', "gtceu:carbon_dioxide 1000", )
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_reactor('benzene_sulfonation')
		.inputFluids('gtceu:benzene 1000', 'gtceu:sulfuric_acid 1000') 
		.itemOutputs('6x gtceu:benzenesulfonic_acid_dust')
		.duration(20*12)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.large_chemical_reactor('benzenesulfonyl_chloride')
		.itemInputs('3x gtceu:benzenesulfonic_acid_dust')
		.inputFluids('gtceu:thionyl_chloride 1000') 
		.outputFluids('gtceu:benzenesulfonyl_chloride 1000', "gtceu:hydrochloric_acid 1000")
		.duration(20*8)
		.EUt((GTValues.VA[GTValues.IV]))

	event.recipes.gtceu.large_chemical_reactor('diphenyl_sulfone_synthesis')
		.inputFluids('gtceu:benzenesulfonyl_chloride 1000', 'gtceu:benzene 2000')
		.notConsumable('gtceu:aluminium_chloride_dust') 
		.outputFluids('gtceu:diphenyl_sulfone 1000', 'gtceu:hydrochloric_acid 2000')
		.duration(20*16)
		.EUt((GTValues.VA[GTValues.UV]))
	
	event.recipes.gtceu.large_chemical_reactor('hydroquinone_synthesis')
		.inputFluids('gtceu:phenol 1000', 'gtceu:hydrogen_peroxide 1000')
		.notConsumable('gtceu:iron_sulfate_dust')
		.outputFluids('gtceu:hydroquinone_solution 2000')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.electric_blast_furnace('hydroquinone_crystallization')
		.inputFluids('gtceu:hydroquinone_solution 10000', 'gtceu:oxygen 2000')
		.circuit(3)
		.blastFurnaceTemp(3003)
		.itemOutputs('5x gtceu:hydroquinone_dust')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.LuV]))
	
	event.recipes.gtceu.chemical_reactor('butynediol_synthesis')
		.inputFluids('gtceu:formaldehyde 2000', 'gtceu:acetylene 1000')
		.notConsumable('gtceu:copper_dust') 
		.notConsumable('gtceu:bismuth_dust')
		.itemOutputs('12x gtceu:butynediol_dust')
		.duration(20*12)
		.EUt((GTValues.VA[GTValues.IV]))
	
	event.recipes.gtceu.chemical_reactor('butanediol_synthesis')
		.inputFluids('gtceu:hydrogen 16000')
		.notConsumable('gtceu:platinum_dust')
		.itemInputs('6x gtceu:butynediol_dust')
		.outputFluids('gtceu:butanediol 500')
		.itemOutputs('7x gtceu:butenediol_dust')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.dehydration_unit('butyrolactone_synthesis')
		.inputFluids('gtceu:butanediol 2000')
		.notConsumable('gtceu:copper_dust')
		.outputFluids('gtceu:butyrolactone 1000', "gtceu:hydrogen 2000")
		.duration(20*20*5)
		.EUt((GTValues.VA[GTValues.ZPM]))
	
	event.recipes.gtceu.large_chemical_reactor('pyrrolidone_synthesis')
		.inputFluids('gtceu:butyrolactone 1000', 'gtceu:ammonia 1000')
		.notConsumable('gtceu:talc_dust')
		.outputFluids('gtceu:pyrrolidone 1000', 'minecraft:water 1000')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.ZPM]))
	
	event.recipes.gtceu.large_chemical_reactor('n_methyl_pyrrolidone_synthesis')
		.inputFluids('gtceu:pyrrolidone 1000', 'gtceu:methanol 1000')
		.notConsumable('gtceu:talc_dust')
		.outputFluids('gtceu:n_methyl_pyrrolidone 1000', 'minecraft:water 1000')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.large_chemical_reactor('peek_polycondensation')
		.itemInputs('3x gtceu:purified_difluorobenzophenone_dust', '6x gtceu:hydroquinone_dust')
		.inputFluids('gtceu:diphenyl_sulfone 2000')
		.notConsumable('gtceu:potassium_carbonate_dust')
		.outputFluids('gtceu:raw_peek_solution 1500')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.dehydration_unit('diphenyl_sulfone_recovery')
		.inputFluids('gtceu:raw_peek_solution 1000', 'gtceu:methanol 2000')
		.itemOutputs('5x gtceu:raw_peek_dust')
		.outputFluids('gtceu:diluted_diphenyl_sulfone 800')
		.duration(20*10*5)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.distillery('peek_precipitation')
		.inputFluids('gtceu:diluted_diphenyl_sulfone 1000')
		.outputFluids('gtceu:diphenyl_sulfone 500')
		.duration(20*5)
		.EUt((GTValues.VA[GTValues.EV]))
		
	event.recipes.gtceu.large_chemical_reactor('peek_purification')
		.itemInputs('32x gtceu:raw_peek_dust')
		.inputFluids('gtceu:n_methyl_pyrrolidone 10000')
		.outputFluids('gtceu:peek 2304', 'gtceu:diluted_n_methyl_pyrrolidone 8000')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UHV]))
	
	event.recipes.gtceu.distillery('n_methyl_pyrrolidone_recovery')
		.inputFluids('gtceu:diluted_n_methyl_pyrrolidone 1000')
		.outputFluids('gtceu:n_methyl_pyrrolidone 500')
		.duration(20*5)
		.EUt((GTValues.VA[GTValues.IV]))

	event.recipes.gtceu.polymerization_chamber('peek_optimized')
        .circuit(1)
        .itemInputs('10x gtceu:hydroquinone_dust')
        .inputFluids('gtceu:difluorobenzophenone 2000')
        .perTick(true)
        .inputFluids('gtceu:n_methyl_pyrrolidone 5')
        .perTick(false)
        .outputFluids('gtceu:peek 2304')
        .duration(20*50*5)
        .EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.chemical_plant('hydroquinone_shortcut')
		.circuit(23)
		.notConsumable('kubejs:chemical_tier_five')
		.inputFluids("gtceu:hydrogen 20000", 'gtceu:phenol 10000', 'gtceu:oxygen 24000')
		.itemOutputs('10x gtceu:hydroquinone_dust')
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_plant('n_methyl_pyrrolidone_shortcut')
		.circuit(23)
		.notConsumable('kubejs:chemical_tier_five')
		.inputFluids("gtceu:butanediol 2000", 'gtceu:ammonia 1000', 'gtceu:methanol 1000')
		.outputFluids('gtceu:n_methyl_pyrrolidone 1000', "minecraft:water 2000")
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_plant('difluorobenzophenone_shortcut')
		.circuit(24)
		.notConsumable('kubejs:chemical_tier_five')
		.inputFluids("gtceu:benzene 4000", 'gtceu:hydrofluoric_acid 2000', 'gtceu:oxygen 2000', "gtceu:methane 2000", "gtceu:chlorine 12000")
		.outputFluids('gtceu:difluorobenzophenone 2000', "gtceu:hydrogen 2000", "gtceu:hydrochloric_acid 12000")
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UIV]))

	
	// Plasma Cracking Oil Proc

	event.recipes.gtceu.extreme_cracking_unit('plasma_cracked_light_fuel')
		.inputFluids('gtceu:light_fuel 10000', 'gtceu:iron_plasma 5000')
		.chancedInput('2x gtceu:neutron_reflector', 5000, 0)
		.chancedInput('2x gtceu:neutron_reflector', 2500, 0)
		.chancedInput('2x gtceu:neutron_reflector', 1250, 0)
		.outputFluids('gtceu:plasmacracked_light_fuel 5000')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UV]))
	
	event.recipes.gtceu.extreme_cracking_unit('plasma_cracked_naphtha')
		.inputFluids('gtceu:naphtha 10000', 'gtceu:nickel_plasma 5000')
		.chancedInput('2x gtceu:neutron_reflector', 5000, 0)
		.chancedInput('2x gtceu:neutron_reflector', 2500, 0)
		.chancedInput('2x gtceu:neutron_reflector', 1250, 0)
		.outputFluids('gtceu:plasmacracked_naphtha 5000')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.extreme_cracking_unit('plasmacracked_heavy_fuel')
		.inputFluids('gtceu:heavy_fuel 10000', 'gtceu:oxygen_plasma 5000')
		.chancedInput('2x gtceu:neutron_reflector', 5000, 0)
		.chancedInput('2x gtceu:neutron_reflector', 2500, 0)
		.chancedInput('2x gtceu:neutron_reflector', 1250, 0)
		.outputFluids('gtceu:plasmacracked_heavy_fuel 5000')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.distillation_tower('plasma_cracked_light_fuel_distillation')
		.inputFluids('gtceu:plasmacracked_light_fuel 1000')
		.cleanroom(CleanroomType.STERILE_CLEANROOM)
		.outputFluids('gtceu:octane 1000', 'gtceu:acetylene 1000', 'gtceu:cumene 1000', 'gtceu:ethylbenzene 1250', 'gtceu:ethanol 1250')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.distillation_tower('plasma_cracked_heavy_fuel_distillation')
		.inputFluids('gtceu:plasmacracked_heavy_fuel 1000')
		.cleanroom(CleanroomType.STERILE_CLEANROOM)
		.outputFluids("gtceu:formaldehyde 1500", 'gtceu:methanol 1250', 'gtceu:acetone 1000', 'gtceu:butyraldehyde 1250', 'gtceu:phenol 1000')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.distillation_tower('plasma_cracked_naphtha_distillation')
		.inputFluids('gtceu:plasmacracked_naphtha 1000')
		.cleanroom(CleanroomType.STERILE_CLEANROOM)
		.outputFluids('gtceu:ethanol 750', 'gtceu:mixed_xylenes 1500', 'gtceu:ethylbenzene 750', 'gtceu:acetylene 500', 'gtceu:cyclopentadiene 1250')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UV]))

	// Carbon Nanotubes

	event.recipes.gtceu.mixer('enriched_carbon_slurry')
		.itemInputs('16x gtceu:exquisite_coke_gem','16x gtceu:exquisite_diamond_gem', '32x gtceu:graphene_dust', '64x gtceu:activated_carbon_dust')
		.inputFluids('gtceu:carbon 10000', 'gtceu:fluoroantimonic_acid 5000')
		.outputFluids('gtceu:enriched_carbon_slurry 20000')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UHV]))
	
	event.recipes.gtceu.extreme_cracking_unit('plasma_cracked_carbon_slurry')
		.inputFluids('gtceu:enriched_carbon_slurry 10000', 'gtceu:thorium_plasma_plasma 5000')
		.chancedInput('2x gtceu:neutron_reflector', 5000, 0)
		.chancedInput('2x gtceu:neutron_reflector', 2500, 0)
		.chancedInput('2x gtceu:neutron_reflector', 1250, 0)
		.outputFluids('gtceu:plasmacracked_carbon_slurry 5000')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.large_chemical_reactor('enriched_carbon_solution')
		.inputFluids('gtceu:plasmacracked_carbon_slurry 1000', 'gtceu:neutronium 2000')
		.outputFluids('gtceu:enriched_carbon_solution 500')
		.circuit(23)
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.large_chemical_reactor('carbon_nanotubes_doped_aluminium_chloride')
		.itemInputs('8x gtceu:aluminium_chloride_dust')
		.inputFluids('gtceu:enriched_carbon_solution 1000', 'gtceu:iron_ii_chloride 500', 'gtceu:ammonia 1000')
		.itemOutputs('16x gtceu:carbon_nanotubes_doped_aluminium_chloride_dust')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.dehydration_unit('raw_carbon_nanotubes_solution')
		.itemInputs('4x gtceu:carbon_nanotubes_doped_aluminium_chloride_dust')
		.inputFluids('gtceu:argon 2500', 'gtceu:methane 1500')
		.outputFluids('gtceu:raw_carbon_nanotubes_solution 2000', 'gtceu:hydrogen 2000')
		.itemOutputs('2x gtceu:aluminium_chloride_dust')
		.duration(20*32*4)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.autoclave('wet_carbon_nanotubes')
		.itemInputs('2x gtceu:carbon_fiber_mesh')
		.inputFluids('gtceu:raw_carbon_nanotubes_solution 1000')
		.itemOutputs('4x gtceu:wet_carbon_nanotubes_foil')
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_bath('carbon_nanotubes_doped_aluminium_chloride')
		.itemInputs('32x gtceu:wet_carbon_nanotubes_foil')
		.inputFluids('gtceu:sulfuric_acid 5000')
		.itemOutputs('8x gtceu:carbon_nanotubes_dust')
		.outputFluids("gtceu:diluted_sulfuric_acid 2500")
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.extruder('carbon_nanotubes_ingot')
		.notConsumable('gtceu:ingot_extruder_mold')
		.itemInputs('1x gtceu:carbon_nanotubes_dust')
		.itemOutputs('1x gtceu:carbon_nanotubes_ingot')
		.duration(10)
		.EUt((GTValues.VA[GTValues.LV]))
	
	event.recipes.gtceu.assembler('filter_frame')
		.itemInputs('4x gtceu:xlpe_rod')
		.itemOutputs('2x kubejs:filter_frame')
		.circuit(2)
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.assembler('carbon_nanotubes_filter')
		.itemInputs('kubejs:filter_frame', '16x gtceu:fine_carbon_nanotubes_wire')
		.itemOutputs('kubejs:carbon_nanotubes_filter')
		.circuit(1)
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.chemical_plant('carbon_nanotubes_shortcut')
		.circuit(22)
		.notConsumable('kubejs:chemical_tier_five')
		.itemInputs('16x gtceu:carbon_fiber_mesh')
		.inputFluids("gtceu:enriched_carbon_slurry 20000", 'gtceu:ammonia 4000', 'gtceu:sulfuric_acid 10000', "gtceu:neutronium 4000", 'gtceu:iron_iii_chloride 6000')
		.itemOutputs('32x gtceu:carbon_nanotubes_dust')
		.duration(20*120)
		.EUt((GTValues.VA[GTValues.UIV]))
	
	//Deep Water Line

	event.recipes.gtceu.chemical_reactor('sodium_hypochlorite')
		.itemInputs("6x gtceu:sodium_hydroxide_dust")
		.inputFluids('gtceu:chlorine 2000')
		.itemOutputs("2x gtceu:salt_dust", "3x gtceu:sodium_hypochlorite_dust")
		.outputFluids("minecraft:water 1000")
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.large_chemical_reactor('chlorocyclopentane')
		.inputFluids('gtceu:chlorine 12000', 'gtceu:cyclopentadiene 1000')
		.outputFluids("gtceu:chlorocyclopentane 1000", "gtceu:hydrochloric_acid 4000")
		.duration(20*55)
		.EUt((GTValues.VA[GTValues.UHV]))
	
	event.recipes.gtceu.dehydration_unit('hexachlorocyclopentadiene')
		.itemInputs("1x gtceu:sodium_hypochlorite_dust")
		.inputFluids('gtceu:chlorocyclopentane 1000')
		.outputFluids("gtceu:hexachlorocyclopentadiene 1000", "gtceu:hydrochloric_acid 2000")
		.duration(20*50*5)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.large_chemical_reactor('endosulfate_synthesis')
		.inputFluids("gtceu:hexachlorocyclopentadiene 1000", "gtceu:thionyl_chloride 1000")
		.itemInputs('7x gtceu:butenediol_dust')
		.itemOutputs('25x gtceu:endosulfate_dust')
		.outputFluids('gtceu:hydrochloric_acid 2000')
		.duration(20*75)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_plant('thionyl_chloride_shortcut')
		.circuit(25)
		.notConsumable('kubejs:chemical_tier_four')
		.itemInputs('1x gtceu:sulfur_dust')
		.inputFluids("gtceu:oxygen 1000", "gtceu:chlorine 2000")
		.outputFluids("gtceu:thionyl_chloride 1000")
		.duration(20*120)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.chemical_plant('endosulfate_shortcut')
		.circuit(23)
		.notConsumable('kubejs:chemical_tier_five')
		.itemInputs('14x gtceu:butenediol_dust')
		.inputFluids("gtceu:cyclopentadiene 2000", 'gtceu:thionyl_chloride 1000', 'gtceu:chlorine 24000')
		.outputFluids('gtceu:hydrochloric_acid 16000')
		.itemOutputs('50x gtceu:endosulfate_dust')
		.duration(20*120)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_bath('deep_water_filtration')
		.itemInputs('16x kubejs:carbon_nanotubes_filter', '500x gtceu:endosulfate_dust')
		.inputFluids('gtceu:deep_water 1000000000')
		.itemOutputsRanged('kubejs:carbon_nanotubes_filter', 2, 8)
		.itemOutputsRanged('kubejs:damaged_carbon_nanotubes_filter', 2, 8)
		.outputFluids('gtceu:filtered_deep_water 800000000')
		.duration(20*600)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.centrifuge('carbon_nanotubes_filter_recycle')
		.itemInputs('kubejs:damaged_carbon_nanotubes_filter')
		.chancedOutput('kubejs:filter_frame', 5000, 0)
		.itemOutputsRanged('gtceu:fine_carbon_nanotubes_wire', 2, 8)
		.duration(20*10)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.evaporation_pool('brine_concentration')
		.inputFluids('gtceu:filtered_deep_water 8000000')
		.outputFluids('gtceu:concentrated_heavy_brine 1000000', 'gtceu:steam 14000000')
		.duration(20*100)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.vacuum_freezer('brine_vacuum_concentration')
		.inputFluids('gtceu:concentrated_heavy_brine 1000')
		.outputFluids('gtceu:super_concentrated_heavy_brine 500')
		.duration(20*5)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_reactor('brine_acidification')
		.inputFluids('gtceu:super_concentrated_heavy_brine 2000', 'gtceu:sulfuric_acid 1000')
		.outputFluids('gtceu:acidified_heavy_brine 3000')
		.duration(20*5)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.chemical_reactor('bromine_oxidation')
		.inputFluids('gtceu:acidified_heavy_brine 2000', 'gtceu:chlorine 1000')
		.outputFluids('gtceu:bromine 500', 'gtceu:depleted_heavy_brine 1500')
		.duration(20*13)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_bath('iodide_adsorption')
		.inputFluids('gtceu:depleted_heavy_brine 1000')
		.itemInputs('4x gtceu:epoxy_plate', '4x gtceu:silver_foil')
		.itemOutputs('4x gtceu:iodide_loaded_resin_plate')
		.outputFluids('gtceu:demineralized_heavy_brine 800')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_reactor('iodide_elution')
		.itemInputs('4x gtceu:iodide_loaded_resin_plate', '3x gtceu:sodium_hydroxide_dust')
		.inputFluids("minecraft:water 1000")
		.outputFluids('gtceu:sodium_iodide_solution 1200')
		.itemOutputs('2x gtceu:epoxy_plate')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.dehydration_unit('iodine_oxidation')
		.inputFluids('gtceu:sodium_iodide_solution 1000', 'gtceu:chlorine 500')
		.outputFluids('gtceu:iodine_suspension 800', 'gtceu:salt_water 700')
		.duration(20*20*5)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.evaporation_pool('iodine_sublimation')
		.inputFluids('gtceu:iodine_suspension 100000')
		.itemOutputs('300x gtceu:iodine_dust')
		.duration(20*100)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.distillation_tower('demineralized_heavy_brine_proc')
		.inputFluids('gtceu:demineralized_heavy_brine 100000')
		.outputFluids('gtceu:heavy_salts_waste 20000', "gtceu:distilled_water 60000", 'gtceu:radon 75000')
		.duration(20*100)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.centrifuge('demineralized_heavy_brine_proc')
		.inputFluids('gtceu:heavy_salts_waste 100000')
		.itemOutputsRanged('gtceu:lithium_chloride_dust', 500, 2000)
		.itemOutputsRanged('gtceu:magnesium_chloride_dust', 500, 2000)
		.itemOutputsRanged('gtceu:aluminium_chloride_dust', 500, 2000)
		.itemOutputsRanged('gtceu:calcium_chloride_dust', 500, 2000)
		.itemOutputsRanged('gtceu:rock_salt_dust', 500, 2000)
		.itemOutputsRanged('gtceu:bauxite_slag_dust', 200, 500)
		.duration(20*50)
		.EUt((GTValues.VA[GTValues.UHV]))

	// ZSM-5

	event.recipes.gtceu.large_chemical_reactor('propylene_hydroformylation')
		.inputFluids('gtceu:ethylene 1000', "gtceu:hydrogen 2000", "gtceu:carbon_monoxide 1000") 
		.notConsumable('gtceu:activated_cobalt_alumina_catalyst_dust')
		.outputFluids('gtceu:propionaldehyde 1500')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.large_chemical_reactor('propionic_acid_synthesis')
		.inputFluids('gtceu:propionaldehyde 1000', 'gtceu:oxygen 1000')
		.notConsumable('gtceu:manganese_acetate_dust')
		.outputFluids('gtceu:propionic_acid 1000')
		.duration(20*32)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.high_pressure_reactor('propylamine_synthesis')
		.inputFluids('gtceu:propionic_acid 1000', 'gtceu:ammonia 2000', 'gtceu:hydrogen 2000')
		.notConsumable('gtceu:nickel_bromide_dust')
		.perTick(true)
		.inputFluids("gtceu:air 250")
		.perTick(false)
		.outputFluids('gtceu:propylamine 1500', 'minecraft:water 1500')
		.duration(20*16)
		.EUt((GTValues.VA[GTValues.IV]))
	
	event.recipes.gtceu.chemical_reactor('tripropylamine_synthesis')
		.inputFluids('gtceu:propylamine 1000', 'gtceu:propene 2000')
		.notConsumable('gtceu:zeolite_dust')
		.outputFluids('gtceu:tripropylamine 1500', 'gtceu:ammonia 500')
		.duration(20*12)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.large_chemical_reactor('bromopropane_synthesis')
		.inputFluids('gtceu:propane 1000', 'gtceu:bromine 2000')
		.notConsumable('gtceu:azo_isobutyronitrile_dust') 
		.outputFluids('gtceu:bromopropane 1000', 'gtceu:hydrogen_bromide 1000')
		.duration(20*24)
		.EUt((GTValues.VA[GTValues.EV]))
	
	event.recipes.gtceu.large_chemical_reactor('tetrapropylammonium_bromide')
		.inputFluids('gtceu:tripropylamine 1000', 'gtceu:bromopropane 1000')
		.outputFluids('gtceu:tetrapropylammonium_bromide_solution 1500')
		.duration(20*12)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_bath('tpab_crystallization')
		.inputFluids('gtceu:tetrapropylammonium_bromide_solution 1000')
		.notConsumable('gtceu:blacklight')
		.itemOutputs('3x gtceu:crude_tetrapropylammonium_bromide_dust')
		.outputFluids('minecraft:water 250')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.chemical_bath('tpab_recrystallization')
		.itemInputs('10x gtceu:crude_tetrapropylammonium_bromide_dust')
		.inputFluids('gtceu:ethanol 1000')
		.itemOutputs('10x gtceu:tetrapropylammonium_bromide_dust')
		.outputFluids('gtceu:diluted_ethanol 500')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.distillation_tower('diluted_ethanol')
		.inputFluids('gtceu:diluted_ethanol 1000')
		.outputFluids('gtceu:ethanol 500', 'minecraft:water 500')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.electric_blast_furnace('sodium_aluminate')
		.itemInputs('5x gtceu:alumina_dust', '6x gtceu:sodium_hydroxide_dust')
		.outputFluids('gtceu:steam 20000')
		.itemOutputs('8x gtceu:sodium_aluminate_dust')
		.duration(20*40)
		.blastFurnaceTemp(1173)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.mixer('zsm_5_solution')
		.itemInputs('6x gtceu:silicon_dioxide_dust', '4x gtceu:sodium_aluminate_dust', '3x gtceu:sodium_hydroxide_dust', '5x gtceu:tetrapropylammonium_bromide_dust')
		.inputFluids("minecraft:water 2000")
		.outputFluids('gtceu:zsm_5_solution 5000')
		.itemOutputs("4x gtceu:certus_quartz_dust")
		.duration(20*40)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.autoclave('zsm_5')
		.itemInputs("16x gtceu:polytetrafluoroethylene_foil")
		.inputFluids("gtceu:zsm_5_solution 2000")
		.itemOutputs("4x gtceu:zsm_5_dust")
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_plant('zsm_5_shortcut')
		.circuit(23)
		.notConsumable('kubejs:chemical_tier_six')
		.itemInputs('6x gtceu:aluminium_dust', '36x gtceu:sodium_hydroxide_dust', '3x gtceu:carbon_dust', '36x gtceu:silicon_dioxide_dust')
		.inputFluids("gtceu:oxygen 18000", 'gtceu:hydrogen 11000', 'gtceu:ammonia 5500', 'gtceu:bromine 7000', 'gtceu:propane 7000', 'gtceu:propene 10000', 'gtceu:ethylene 14000')
		.itemOutputs('64x gtceu:zsm_5_dust')
		.duration(20*120)
		.EUt((GTValues.VA[GTValues.OpV]))

	// Kevlar

  	event.recipes.gtceu.centrifuge('p_xylene_separation')
		.inputFluids('gtceu:mixed_xylenes 10000')
		.itemInputs('2x gtceu:zsm_5_dust')
		.outputFluids('gtceu:p_xylene 8000', 'gtceu:o_xylene 1000', 'gtceu:m_xylene 1000')
		.duration(20*50)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.large_chemical_reactor('ta_synthesis')
		.inputFluids('gtceu:p_xylene 1000', 'gtceu:oxygen 3000')
		.notConsumable('gtceu:cobalt_permanganate_dust')
		.outputFluids('gtceu:terephthalic_acid_slurry 1500')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.dehydration_unit('ta_purification')
		.inputFluids('gtceu:terephthalic_acid_slurry 1000')
		.itemOutputs('3x gtceu:crude_terephthalic_acid_dust')
		.outputFluids("minecraft:water 500")
		.duration(20*35*5)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.high_pressure_reactor('ta_hydrogenation')
		.itemInputs('3x gtceu:crude_terephthalic_acid_dust')
		.inputFluids('gtceu:hydrogen 1000')
		.notConsumable('gtceu:palladium_dust')
		.perTick(true)
		.inputFluids("gtceu:air 250")
		.perTick(false)
		.itemOutputs('3x gtceu:terephthalic_acid_dust')
		.duration(20*5)
		.EUt((GTValues.VA[GTValues.UIV]))
	
	event.recipes.gtceu.large_chemical_reactor('tcl_synthesis')
		.itemInputs('3x gtceu:terephthalic_acid_dust')
		.inputFluids('gtceu:thionyl_chloride 4000')
		.outputFluids('gtceu:terephthaloyl_chloride 1000', 'gtceu:sulfur_dioxide 1000', 'gtceu:hydrochloric_acid 1000')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.high_pressure_reactor('p_nitroaniline_synthesis')
		.inputFluids("gtceu:nitrochlorobenzene 1000", 'gtceu:ammonia 2000')
		.notConsumable('gtceu:copper_chromite_dust')
		.perTick(true)
		.inputFluids("gtceu:air 250")
		.perTick(false)
		.itemOutputs('3x gtceu:p_nitroaniline_dust', "2x gtceu:ammonium_chloride_dust")
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.large_chemical_reactor('ppd_reduction')
		.itemInputs('3x gtceu:p_nitroaniline_dust')
		.inputFluids('gtceu:hydrogen 3000')
		.notConsumable('gtceu:nickel_bromide_dust')
		.outputFluids('gtceu:p_phenylenediamine_solution 1500')
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.distillation_tower('ppd_purification')
		.inputFluids('gtceu:p_phenylenediamine_solution 1000')
		.outputFluids('gtceu:p_phenylenediamine 700', "minecraft:water 300")
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.polymerization_chamber('kevlar_polymer_solution')
		.inputFluids('gtceu:terephthaloyl_chloride 1500', 'gtceu:p_phenylenediamine 1500')
		.itemInputs("6x gtceu:calcium_chloride_dust")
		.perTick(true)
        .inputFluids('gtceu:n_methyl_pyrrolidone 10')
        .perTick(false)
		.outputFluids('gtceu:kevlar_polymer_solution 2000')
		.duration(20*50*5)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_plant('p_phenylenediamine_shortcut')
		.circuit(21)
		//.notConsumable('kubejs:chemical_tier_seven')
		.inputFluids("gtceu:chlorine 8000", 'gtceu:hydrogen 12000', 'gtceu:ammonia 8000', 'gtceu:benzene 4000', 'gtceu:nitration_mixture 8000')
		.itemOutputs("8x gtceu:ammonium_chloride_dust")
		.outputFluids('gtceu:p_phenylenediamine 4200', 'gtceu:hydrochloric_acid 4000', 'gtceu:diluted_sulfuric_acid 4000')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.OpV]))
		
	event.recipes.gtceu.chemical_plant('terephthaloyl_chloride_shortcut')
		.circuit(25)
		//.notConsumable('kubejs:chemical_tier_seven')
		.itemInputs('2x gtceu:zsm_5_dust')
		.inputFluids("gtceu:oxygen 24000", 'gtceu:hydrogen 12000', 'gtceu:thionyl_chloride 48000', 'gtceu:mixed_xylenes 10000', 'gtceu:nitration_mixture 8000')
		.outputFluids('gtceu:terephthaloyl_chloride 12000', 'gtceu:hydrochloric_acid 12000', 'gtceu:sulfur_dioxide 12000', 'minecraft:water 6000')
		.duration(20*45)
		.EUt((GTValues.VA[GTValues.OpV]))

	event.recipes.gtceu.vacuum_freezer('kevlar_polymer_degrading')
		.inputFluids('gtceu:kevlar_polymer_solution 1000')
		.outputFluids('gtceu:degassed_kevlar_solution 900')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.radiation_chamber('kevlar_fiber_formation')
		.inputFluids('gtceu:degassed_kevlar_solution 1000')
		.itemInputs('32x gtceu:fine_carbon_nanotubes_wire')
		.chancedInput('4x gtceu:awakened_draconium_bolt', 2500, 0)
		.itemOutputs('8x kubejs:wet_kevlar_fibers')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_plant('kevlar_treating_bad')
		.itemInputs('32x kubejs:wet_kevlar_fibers')
		.notConsumable('kubejs:chemical_tier_five')
		.inputFluids('gtceu:hypercharged_oganesson_plasma 1000', "gtceu:antimatter 10000")
		.itemOutputs('16x kubejs:treated_kevlar_fibers')
		.duration(20*120)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_plant('kevlar_treating_good')
		.itemInputs('32x kubejs:wet_kevlar_fibers')
		.notConsumable('kubejs:chemical_tier_five')
		.inputFluids('gtceu:naquadria_plasma_mk2_plasma 1000', "gtceu:antimatter 5000")
		.itemOutputs('24x kubejs:treated_kevlar_fibers')
		.duration(20*90)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_plant('kevlar_treating_best')
		.itemInputs('32x kubejs:wet_kevlar_fibers')
		.notConsumable('kubejs:chemical_tier_five')
		.inputFluids('gtceu:naquadria_plasma_mk3_plasma 1000', "gtceu:antimatter 2500")
		.itemOutputs('32x kubejs:treated_kevlar_fibers')
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.quantum_cooling_chamber('kevlar_drying')
		.itemInputs('4x kubejs:treated_kevlar_fibers')
		.inputFluids("gtceu:cryogenic_neutron_flow 576", "gtceu:stropharic_hypoxylon 1500")
		.itemOutputs('4x kubejs:kevlar_fibers')
		.duration(20*1)
		.EUt((GTValues.VA[GTValues.UXV]))

	event.recipes.gtceu.atomiccompressor('kevlar_pressing')
		.itemInputs('4x kubejs:kevlar_fibers')
		.itemOutputs('gtceu:kevlar_plate')
		.duration(20*5)
		.EUt((GTValues.VA[GTValues.UXV]))

	event.recipes.gtceu.extruder('kevlar_ingot')
		.notConsumable('gtceu:ingot_extruder_mold')
		.itemInputs('1x gtceu:kevlar_dust')
		.itemOutputs('1x gtceu:kevlar_ingot')
		.duration(10)
		.EUt((GTValues.VA[GTValues.LV]))

	event.recipes.gtceu.plasma_nexus('kevlar_melting')
		.itemInputs('4x gtceu:kevlar_dust', '16x gtceu:carbon_nanotubes_dust')
		.inputFluids("gtceu:antimatter 750", "gtceu:hypercharged_nihonium_plasma 125")
		.outputFluids('gtceu:meta_stable_molten_kevlar 576')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.UXV]))

	// Zylon

	event.recipes.gtceu.extreme_cracking_unit('plasmacracked_coal_tar')
		.inputFluids('gtceu:coal_tar 10000', 'gtceu:americium_plasma 5000')
		.chancedInput('2x gtceu:neutron_reflector', 5000, 0)
		.chancedInput('2x gtceu:neutron_reflector', 2500, 0)
		.chancedInput('2x gtceu:neutron_reflector', 1250, 0)
		.outputFluids('gtceu:plasmacracked_coal_tar 5000')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.distillation_tower('coal_tar_pyridine_extraction')
		.inputFluids('gtceu:plasmacracked_coal_tar 1000')
		.cleanroom(CleanroomType.STERILE_CLEANROOM)
		.outputFluids("gtceu:pyridine_bases 500", "gtceu:ethylbenzene 1500", "gtceu:ammonia 500")
		.duration(20*40)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_reactor('pyridine_acid_extraction')
		.inputFluids('gtceu:pyridine_bases 1000', 'gtceu:sulfuric_acid 1000')
		.outputFluids('gtceu:pyridine_sulfate_solution 1500')
		.duration(20*28)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.chemical_reactor('pyridine_liberation')
		.itemInputs("3x gtceu:sodium_hydroxide_dust")
		.inputFluids('gtceu:pyridine_sulfate_solution 1000', 'minecraft:water 500')
		.itemOutputs("3x gtceu:sodium_bisulfate_dust")
		.outputFluids('gtceu:crude_pyridine 800')
		.duration(20*32)
		.EUt((GTValues.VA[GTValues.LuV]))

	event.recipes.gtceu.dehydration_unit('acetaldehyde_synthesis')
		.inputFluids('gtceu:ethanol 1000', 'gtceu:oxygen 2000')
		.notConsumable("gtceu:silver_dust")
		.outputFluids('gtceu:acetaldehyde 2000', 'minecraft:water 2000')
		.duration(20*35*4)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.large_chemical_reactor('pyridine_aldehyde_synthesis')
		.inputFluids('gtceu:acetaldehyde 1500', 'gtceu:ammonia 1000', 'gtceu:formaldehyde 500')
		.notConsumable("gtceu:alumina_dust")
		.notConsumable("gtceu:silicon_dioxide_dust")
		.outputFluids('gtceu:synthetic_pyridine_mixture 2000')
		.duration(20*47)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.distillation_tower('synthetic_pyridine_separation')
		.inputFluids('gtceu:synthetic_pyridine_mixture 1000')
		.outputFluids('gtceu:crude_synthetic_pyridine 750', 'minecraft:water 500', "gtceu:ammonium_formate 250")
		.duration(20*29)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.mixer('technical_pyridine_mixing')
		.inputFluids('gtceu:crude_pyridine 1000', 'gtceu:crude_synthetic_pyridine 1000')
		.outputFluids('gtceu:technical_pyridine_mixture 2000')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.HV]))

	event.recipes.gtceu.dehydration_unit('pyridine_drying_technical')
		.inputFluids('gtceu:technical_pyridine_mixture 1000', 'gtceu:toluene 200')
		.outputFluids('gtceu:dry_technical_pyridine 1000', 'gtceu:water_toluene_azeotrope 200')
		.duration(20*39*4)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.distillation_tower('water_toluene_azeotrope_separation')
		.inputFluids('gtceu:water_toluene_azeotrope 1000')
		.outputFluids('gtceu:toluene 750', 'minecraft:water 250')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.distillation_tower('pyridine_95_purification')
		.inputFluids('gtceu:dry_technical_pyridine 1000')
		.outputFluids('gtceu:pure_pyridine 800', 'gtceu:lutidine 50')
		.itemOutputs('2x gtceu:picoline_dust')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.chemical_reactor('chloropyridine_solution_synthesis')
		.inputFluids('gtceu:pure_pyridine 2000', 'gtceu:chlorine 6000', "gtceu:steam 2000")
		.outputFluids('gtceu:chloropyridine_solution 2000')
		.duration(20*45)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.distillation_tower('chloropyridine_solution_distillation')
		.inputFluids('gtceu:chloropyridine_solution 1000')
		.itemOutputs('4x gtceu:dichloropyridine_dust')
		.outputFluids('gtceu:chloropyridine 500', 'gtceu:hydrochloric_acid 1500')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.UXV]))

	event.recipes.gtceu.chemical_reactor('dichloropyridine_synthesis')
		.inputFluids('gtceu:chloropyridine 1000', 'gtceu:chlorine 2000')
		.itemOutputs('8x gtceu:dichloropyridine_dust')
		.outputFluids('gtceu:hydrochloric_acid 1000')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.dehydration_unit('diethyl_ether_synthesis')
		.inputFluids('gtceu:ethanol 2000')
		.notConsumable('gtceu:alumina_dust')
		.outputFluids('gtceu:diethyl_ether 1000', 'minecraft:water 1000')
		.duration(20*35*3)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.large_chemical_reactor('2-6_bischloromagnesiopyridine_synthesis')
		.inputFluids('gtceu:diethyl_ether 250')
		.itemInputs('32x gtceu:dichloropyridine_dust', '1x gtceu:small_iodine_dust', '4x gtceu:magnesium_dust')
		.outputFluids('gtceu:2-6_bischloromagnesiopyridine 2000')
		.duration(20*45)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.large_chemical_reactor('magnesium_pyridine_2-6_dicarboxylate_synthesis')
		.inputFluids('gtceu:2-6_bischloromagnesiopyridine 1000', "gtceu:carbon_dioxide 2000")
		.itemOutputs("6x gtceu:magnesium_pyridine_2-6_dicarboxylate_dust", "3x gtceu:magnesium_chloride_dust")
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.large_chemical_reactor('dipicolinic_acid_dus_from_magnesium_pyridine_2-6_dicarboxylate')
		.inputFluids("gtceu:hydrochloric_acid 2000")
		.itemInputs("6x gtceu:magnesium_pyridine_2-6_dicarboxylate_dust")
		.itemOutputs("17x gtceu:dipicolinic_acid_dust", "3x gtceu:magnesium_chloride_dust")
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.large_chemical_reactor('picolinic_acid_slurry')
		.inputFluids('gtceu:oxygen 3000', 'gtceu:ammonia 1000')
		.itemInputs('14x gtceu:picoline_dust')
		.notConsumable('gtceu:cobalt_oxide_dust')
		.outputFluids('gtceu:picolinic_acid_slurry 1000', 'minecraft:water 1000')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.electrolyzer('picolinic_acid_synthesis')
		.inputFluids('gtceu:picolinic_acid_slurry 1000')
		.itemOutputs("14x gtceu:picolinic_acid_dust")
		.outputFluids('gtceu:ammonia 1000')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.high_pressure_reactor('dipicolinic_acid_from_picolinic_acid')
		.inputFluids("gtceu:carbon_dioxide")
		.itemInputs("14x gtceu:picolinic_acid_dust")
		.perTick(true)
		.inputFluids("gtceu:air 250")
		.perTick(false)
		.itemOutputs("17x gtceu:dipicolinic_acid_dust")
		.duration(20*120)
		.EUt((GTValues.VA[GTValues.UEV]))
	
	event.recipes.gtceu.large_chemical_reactor('potassium_permanganate')
		.inputFluids("minecraft:water 2000")
		.itemInputs("21x gtceu:potassium_manganate_dust")
		.itemOutputs("12x gtceu:potassium_permanganate_dust", "3x gtceu:pyrolusite_dust", "12x gtceu:sodium_hydroxide_dust")
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.large_chemical_reactor('potassium_dipicolinate')
		.inputFluids("gtceu:lutidine 1000", "minecraft:water 2000")
		.itemInputs("6x gtceu:potassium_permanganate_dust")
		.itemOutputs("19x gtceu:potassium_dipicolinate_dust", "3x gtceu:pyrolusite_dust")
		.outputFluids('gtceu:hydrogen 10000')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.large_chemical_reactor('dipicolinic_acid_from_potassium_dipicolinate')
		.inputFluids("gtceu:hydrochloric_acid 2000")
		.itemInputs("19x gtceu:potassium_dipicolinate_dust")
		.itemOutputs("17x gtceu:dipicolinic_acid_dust", "4x gtceu:rock_salt_dust")
		.duration(20*55)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_reactor('phosphorus_trichloride')
		.inputFluids('gtceu:chlorine 12000')
		.circuit(3)
		.itemInputs("4x gtceu:phosphorus_dust")
		.outputFluids('gtceu:phosphorus_trichloride 4000')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.EV]))

	event.recipes.gtceu.chemical_reactor('phosphorus_pentachloride')
		.inputFluids('gtceu:phosphorus_trichloride 1000', 'gtceu:chlorine 2000')
		.itemOutputs('6x gtceu:phosphorus_pentachloride_dust')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.large_chemical_reactor('dipicolinyl_dichloride_synthesis')
		.itemInputs('34x gtceu:dipicolinic_acid_dust', '12x gtceu:phosphorus_pentachloride_dust')
		.inputFluids('gtceu:thionyl_chloride 1000')
		.outputFluids('gtceu:dipicolinyl_dichloride_solution 1500', 'gtceu:phosphorus_oxychloride 1000', 'gtceu:hydrochloric_acid 1000')
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.high_pressure_reactor('dipicolinyl_dichloride_recrystallization')
		.inputFluids('gtceu:dipicolinyl_dichloride_solution 1000', 'gtceu:ethanol 500')
		.perTick(true)
		.inputFluids("gtceu:air 250")
		.perTick(false)
		.itemOutputs('7x gtceu:dipicolinyl_dichloride_dust')
		.duration(20*20)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.mixer('pentose_enriched_biomass')
		.inputFluids("gtceu:biomass 3000", "gtceu:wood_vinegar 2000")
		.itemInputs("64x gtceu:wheat_dust", "48x minecraft:sugar")
		.outputFluids('gtceu:pentose_enriched_biomass 5000')
		.duration(20*46)
		.EUt((GTValues.VA[GTValues.ZPM]))

	event.recipes.gtceu.distillation_tower('pentose_enriched_biomass_distillation')
		.inputFluids("gtceu:pentose_enriched_biomass 1000")
		.outputFluids('gtceu:xylose 500', 'gtceu:wood_gas 250', 'gtceu:fermented_biomass 250')
		.duration(20*60)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.dehydration_unit('furfural_synthesis')
		.inputFluids('gtceu:xylose 1000', 'gtceu:diluted_sulfuric_acid 500')
		.notConsumable('gtceu:alumina_dust')
		.outputFluids('gtceu:furfural 1000', 'minecraft:water 3000')
		.duration(20*45*3)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.chemical_reactor('fumaric_acid_synthesis')
		.inputFluids('gtceu:furfural 1000', 'gtceu:oxygen 3000')
		.notConsumable('gtceu:vanadium_dust')
		.itemOutputs('12x gtceu:fumaric_acid_dust')
		.outputFluids('gtceu:carbon_monoxide 1000')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.high_pressure_reactor('diiminosuccinonitrile')
		.inputFluids('gtceu:ammonia 3000')
		.itemInputs('12x gtceu:fumaric_acid_dust')
		.notConsumable('gtceu:zeolite_dust')
		.perTick(true)
		.inputFluids("gtceu:air 250")
		.perTick(false)
		.outputFluids('gtceu:diiminosuccinonitrile 1500')
		.duration(20*55)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.dehydration_unit('pyrazine_cyclization')
		.inputFluids('gtceu:diiminosuccinonitrile 1000')
		.notConsumable('gtceu:aluminium_chloride_dust')
		.outputFluids('gtceu:pyrazine 600', 'gtceu:ammonia 400')
		.duration(20*25*4)
		.EUt((GTValues.VA[GTValues.UIV]))

	event.recipes.gtceu.large_chemical_reactor('pyrazine_dicarboxylic_acid')
		.inputFluids('gtceu:pyrazine 2000', 'gtceu:oxygen 5000')
		.notConsumable('gtceu:platinum_dust')
		.outputFluids("gtceu:hydrogen_cyanide 2000", "minecraft:water 1000")
		.itemOutputs('16x gtceu:pyrazine_dicarboxylic_acid_dust')
		.duration(20*35)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.large_chemical_reactor('pyrazine_dichloride')
		.itemInputs('16x gtceu:pyrazine_dicarboxylic_acid_dust', '18x gtceu:phosphorus_pentachloride_dust')
		.inputFluids("gtceu:distilled_water 500")
		.outputFluids('gtceu:pyrazine_dicarbonyl_dichloride 1000', 'gtceu:phosphorus_oxychloride 2000')
		.duration(20*15)
		.EUt((GTValues.VA[GTValues.UXV]))

	event.recipes.gtceu.dehydration_unit('pyrophosphoric_acid')
		.inputFluids("gtceu:phosphoric_acid 2000")
		.outputFluids('gtceu:pyrophosphoric_acid 1000', "minecraft:water 1000")
		.duration(20*15*3)
		.EUt((GTValues.VA[GTValues.UV]))

	event.recipes.gtceu.chemical_reactor('triphosphoric_acid')
		.inputFluids("gtceu:phosphoric_acid 1000", "gtceu:pyrophosphoric_acid 1000")
		.outputFluids('gtceu:triphosphoric_acid 1000', "minecraft:water 1000")
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.UHV]))

	event.recipes.gtceu.chemical_reactor('tetraphosphoric_acid')
		.inputFluids("gtceu:phosphoric_acid 1000", "gtceu:triphosphoric_acid  1000")
		.outputFluids('gtceu:tetraphosphoric_acid 1000', "minecraft:water 1000")
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.UEV]))

	event.recipes.gtceu.polymerization_chamber('zylon_polymerization')
		.inputFluids('gtceu:pyrazine_dicarbonyl_dichloride 500')
		.itemInputs('7x gtceu:dipicolinyl_dichloride_dust')
		.perTick(true)
		.inputFluids('gtceu:tetraphosphoric_acid 10')
		.perTick(false)
		.outputFluids('gtceu:zylon_polymer_solution 2000')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.OpV]))

	event.recipes.gtceu.quantum_cooling_chamber('zylon_degrading')
		.inputFluids('gtceu:zylon_polymer_solution 1000', 'gtceu:cryogenic_neutron_flow 72')
		.outputFluids('gtceu:degassed_zylon_solution 950')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.UXV]))

	event.recipes.gtceu.chemical_plant('zylon_treating')
		.inputFluids("gtceu:degassed_zylon_solution 5000", "gtceu:cosmic_tungsten 576", "gtceu:cosmic_osmium 576", "gtceu:naquadria_plasma_mk3_plasma 1500")
		.itemInputs("4x gtceu:space_time_dust")
		.notConsumable('kubejs:chemical_tier_six')
		.outputFluids('gtceu:treated_zylon_polymer_solution 6000')
		.duration(20*150)
		.EUt((GTValues.VA[GTValues.OpV]))

	event.recipes.gtceu.radiation_chamber('zylon_plate')
		.inputFluids('gtceu:treated_zylon_polymer_solution 1000', 'gtceu:n_methyl_pyrrolidone 1500')
		.chancedInput("4x gtceu:pure_cosmic_matter_bolt", 2500, 0)
		.notConsumable('gtceu:plate_casting_mold')
		.itemOutputs('8x gtceu:zylon_plate')
		.outputFluids('gtceu:diluted_n_methyl_pyrrolidone 500')
		.duration(20*30)
		.EUt((GTValues.VA[GTValues.OpV]))

	event.recipes.gtceu.extruder('zylon_ingot')
		.notConsumable('gtceu:ingot_extruder_mold')
		.itemInputs('1x gtceu:zylon_dust')
		.itemOutputs('1x gtceu:zylon_ingot')
		.duration(10)
		.EUt((GTValues.VA[GTValues.LV]))

	event.recipes.gtceu.plasma_nexus('zylon_melting')
		.itemInputs('4x gtceu:zylon_dust', '32x gtceu:carbon_nanotubes_dust')
		.inputFluids("gtceu:antimatter 1500", "gtceu:hypercharged_nebular_plasma 500")
		.outputFluids('gtceu:meta_stable_molten_zylon 576')
		.duration(20*25)
		.EUt((GTValues.VA[GTValues.OpV]))

})


