Platform.mods.kubejs.name = 'GregTech';
Platform.mods.bloodmagic.name = 'GregTechBM';

StartupEvents.registry('item', sog => {
    //Universal circuits
        const tiers = ["ulv", "lv", "mv", "hv", "ev", "iv", "luv", "zpm", "uv", "uhv", "uev", "uiv"]
        tiers.forEach((universal_circuit) => {
            sog.create(universal_circuit + "_universal_circuit")
                .tag("gtceu:circuits/" + universal_circuit)
                .tag("gtceu:circuits/universal")
                .displayName(universal_circuit.toUpperCase() + " Universal Circuit")
                .tooltip("§7A Universal Circuit")
                .textureJson({ layer0: `kubejs:item/universal_circuit/${universal_circuit}_universal_circuit` })
        })

    // Circuit stuff
    sog.create('star_extruder_mold').maxStackSize(64).glow(true).displayName('Extruder Mold (Star)')
    sog.create('resonant_processor').maxStackSize(64).displayName('Resonant Processor').tooltip('§2ZPM-Tier Circuit')
    sog.create('resonant_processor_assembly').maxStackSize(64).displayName('Resonant Processor Assembly').tooltip('§2UV-Tier Circuit')
    sog.create('resonant_processor_computer').maxStackSize(64).displayName('Resonant Processor Computer').tooltip('§2UHV-Tier Circuit')
    sog.create('resonant_processor_mainframe').maxStackSize(64).displayName('Resonant Processor Mainframe').tooltip('§2UEV-Tier Circuit')
    sog.create('dragon_processor').maxStackSize(64).displayName('Dragon Processor').tooltip('§5UV-Tier Circuit')
    sog.create('dragon_processor_assembly').maxStackSize(64).displayName('Dragon Processor Assembly').tooltip('§5UHV-Tier Circuit')
    sog.create('dragon_processor_computer').maxStackSize(64).displayName('Dragon Processor Computer').tooltip('§5UEV-Tier Circuit')
    sog.create('dragon_processor_mainframe').maxStackSize(64).displayName('Dragon Processor Mainframe').tooltip('§5UIV-Tier Circuit')
    sog.create('cosmic_processor').maxStackSize(64).displayName('Cosmic Processor').tooltip('§0UHV-Tier Circuit')
    sog.create('cosmic_processor_assembly').maxStackSize(64).displayName('Cosmic Processor Assembly').tooltip('§0UEV-Tier Circuit')
    sog.create('cosmic_processor_computer').maxStackSize(64).displayName('Cosmic Processor Computer').tooltip('§0UIV-Tier Circuit')
    sog.create('cosmic_processor_mainframe').maxStackSize(64).displayName('Cosmic Processor Mainframe').tooltip('§0UXV-Tier Circuit')
    sog.create('chrono_infinity_processor').maxStackSize(64).displayName('Chrono-Infinity Processor').tooltip('§bUEV-Tier Circuit')
    sog.create('chrono_infinity_processor_assembly').maxStackSize(64).displayName('Chrono-Infinity Processor Assembly').tooltip('§bUIV-Tier Circuit')
    sog.create('chrono_infinity_processor_computer').maxStackSize(64).displayName('Chrono-Infinity Processor Computer').tooltip('§bUXV-Tier Circuit')
    sog.create('chrono_infinity_processor_mainframe').maxStackSize(64).displayName('Chrono-Infinity Processor Mainframe').tooltip('§bOPV-Tier Circuit')
    sog.create('chrono_infinity_printed_circuit_board').maxStackSize(64).displayName('Chrono-Infinity Printed Circuit Board')
    sog.create('dimensional_circuit_board').maxStackSize(64).displayName('Dimensional Circuit Board').rarity('epic')
    sog.create('dimensional_printed_circuit_board').maxStackSize(64).displayName('Dimensional Printed Circuit Board').rarity('epic')
    sog.create('dimensional_processor').maxStackSize(64).displayName('Dimensional Processor').tooltip('§f§lUIV-Tier Circuit').rarity('epic')
    sog.create('dimensional_processor_assembly').maxStackSize(64).displayName('Dimensional Processor Assembly').tooltip('§f§lUXV-Tier Circuit').rarity('epic')
    sog.create('dimensional_processor_computer').maxStackSize(64).displayName('Dimensional Processor Computer').tooltip('§f§lOPV-Tier Circuit').rarity('epic')
    sog.create('dimensional_processor_mainframe').maxStackSize(64).displayName('Dimensional Processor Mainframe').tooltip('§f§lMAX-Tier Circuit').rarity('epic')

    // Polymers & PCB stuff 
    sog.create('filter_frame').maxStackSize(64).displayName('Filter Frame')
    sog.create('carbon_nanotubes_filter').maxStackSize(64).displayName('Carbon Nanotubes Filter')
    sog.create('damaged_carbon_nanotubes_filter').maxStackSize(64).displayName('Damaged Carbon Nanotubes Filter')
    sog.create('kevlar_fibers').maxStackSize(64).displayName('Kevlar Fibers')
    sog.create('wet_kevlar_fibers').maxStackSize(64).displayName('Wet Kevlar Fibers')
    sog.create('treated_kevlar_fibers').maxStackSize(64).displayName('Treated Kevlar Fibers')
    sog.create('emitter_red').maxStackSize(64).displayName('§4Laser Flux Emitter(Red)').glow(true)
    sog.create('emitter_blue').maxStackSize(64).displayName('§1Laser Flux Emitter(Blue)').glow(true)
    sog.create('emitter_green').maxStackSize(64).displayName('§aLaser Flux Emitter(Green)').glow(true)
    sog.create('sapphire_boule').maxStackSize(64).displayName('Sapphire Boule')
    sog.create('sapphire_wafer').maxStackSize(64).displayName('Sapphire Wafer')
    sog.create('perfectly_polished_sapphire_wafer').maxStackSize(64).displayName('Perfectly Polished Sapphire Wafer')
    sog.create('silver_doped_sapphire_wafer').maxStackSize(64).displayName('Silver Doped Sapphire Wafer')
    sog.create('ultra_reflective_sapphire_wafer').maxStackSize(64).displayName('Ultra Reflective Sapphire Wafer').glow(true)
    sog.create('multispectral_monochrome_mirror').maxStackSize(64).displayName('Multispectral Monochrome Mirror').glow(true)
    sog.create('space_time_distorting_ultimate_mirror').maxStackSize(64).displayName('Space-Time Distorting Ultimate Mirror').glow(true)
    sog.create('red_spectre_ultimate_mirror').maxStackSize(64).displayName('§4Red Spectre Ultimate Mirror').glow(true)
    sog.create('blue_spectre_ultimate_mirror').maxStackSize(64).displayName('§1Blue Spectre Ultimate Mirror').glow(true)
    sog.create('green_spectre_ultimate_mirror').maxStackSize(64).displayName('§aGreen Spectre Ultimate Mirror').glow(true)
    sog.create('laser_containment_cell_red').maxStackSize(64).displayName('§4Laser Flux Containment Capsule(Red)').glow(true)
    sog.create('laser_containment_cell_blue').maxStackSize(64).displayName('§1Laser Flux Containment Capsule(Blue)').glow(true)
    sog.create('laser_containment_cell_green').maxStackSize(64).displayName('§aLaser Flux Containment Capsule(Green)').glow(true)
    // Condensed & Atomic Stuff
    sog.create('condensed_star_matter').maxStackSize(64).displayName('Condensed Star Matter').tooltip('Matter of gods')
    sog.create('quantum_energy_capsule').maxStackSize(64).displayName('Quantum Energy Capsule').tooltip('Not safe for work')
    sog.create('gravitational_containment_cell').maxStackSize(64).displayName('Gravitational Containment Cell')
    sog.create('gravitational_fluctuation_module').maxStackSize(64).displayName('Gravitational Fluctuation Module')
    sog.create('exotic_matter').maxStackSize(64).displayName('§5Exotic Matter')
    sog.create('stable_matter').maxStackSize(64).displayName('Stable Matter')
    sog.create('atomically_compressed_black_hole').maxStackSize(64).displayName('Atomically-Compressed Black Hole').tooltip('§0Hold with caution. Maintains an Event Horizon')
    sog.create('quantum_resonant_core').maxStackSize(64).displayName('Quantum Resonant Core')
    // Singularities Stuff 
    sog.create('quantum_anomaly').maxStackSize(64).displayName('Quantum Anomaly').glow(true).tooltip('Not safe for work')
    sog.create('energized_quantum_anomaly').maxStackSize(64).displayName('Energized Anomaly').glow(true)
    sog.create('stabilized_collapsed_singularity').maxStackSize(64).displayName('Stabilized Collapsed Singularity')    
    sog.create('fallen_singularity').maxStackSize(64).displayName('Fallen Singularity').tooltip('§cNot-Stabilized Collapsed Singularity')
    // Voltage coils
    sog.create('uhv_voltage_coil').maxStackSize(64).displayName('Ultra High Voltage Coil')
    sog.create('uev_voltage_coil').maxStackSize(64).displayName('Ultra Excessive Voltage Coil')
    sog.create('uiv_voltage_coil').maxStackSize(64).displayName('Ultra Immense Voltage Coil')
    sog.create('uxv_voltage_coil').maxStackSize(64).displayName('Ultra Extreme Voltage Coil')
    sog.create('opv_voltage_coil').maxStackSize(64).displayName('Overpowered Voltage Coil')
    sog.create('max_voltage_coil').maxStackSize(64).displayName('Max Voltage Coil').rarity('epic')
    // UEV stuff
    sog.create('rad_primary_resonant_particles').maxStackSize(16).displayName('Rad-Primary Resonant Particles')
    sog.create('primal_resonant_core').maxStackSize(64).displayName('Primal Resonant Core')
    sog.create('antimatter_boule').maxStackSize(64).displayName('Antimatter-Doped Monocrystalline Silicon Boule')
    sog.create('highly_resonative_soc').maxStackSize(64).displayName('Highly-Resonative Soc')
    sog.create('highly_resonative_circuit_board').maxStackSize(64).displayName('Highly-Resonative Circuit Board')
    sog.create('highly_resonative_printed_circuit_board').maxStackSize(64).displayName('Highly-Resonative Printed Circuit Board')
    // UIV stuff
    sog.create('dragon_infused_neuro_processing_unit').maxStackSize(64).displayName('Dragon-infused Neuro Processing Board')
    sog.create('draconic_circuit_board').maxStackSize(64).displayName('Draconic Circuit Board')
    sog.create('draconic_printed_circuit_board').maxStackSize(64).displayName('Draconic Printed Circuit Board')
    sog.create('antimatter_wafer').maxStackSize(64).displayName('Antimatter Wafer')
    sog.create('highly_draconized_engraved_lapotron_crystal_chip').maxStackSize(64).displayName('Highly-Draconized Engraved Lapotron Chip')
    sog.create('extremely_advanced_soc_wafer').maxStackSize(64).displayName('EaSoC Wafer')
    sog.create('extremely_advanced_soc').maxStackSize(64).displayName('EaSoC')
    // Extras
    sog.create('end_miner_module').maxStackSize(1).displayName('End Miner Module')
    sog.create('quantum_data_module').maxStackSize(1).displayName('Quantum Data Module').texture('kubejs:item/misc/quantum_data_module')
    // Tube
    sog.create('chlorine_tube').maxStackSize(1).displayName('Chlorine Tube').texture('kubejs:item/tubes/chlorine_tube')
    sog.create('mycena_hypsizyga_dna').maxStackSize(1).displayName('Mycena Hypsizyga DNA Sample').texture('kubejs:item/tubes/dna_sample_mychyps')
    // Heavy plating
    sog.create('cosmic_neutronium_heavy_plating').displayName('Cosmic Neutronium Heavy Plating').texture('kubejs:item/heavy_plating/cosmic_neutronium_heavy_plating')
    sog.create('awakened_draconium_heavy_plating').displayName('Awakened Draconium Heavy Plating').texture('kubejs:item/heavy_plating/awakened_draconium_heavy_plating')
    sog.create('draconium_heavy_plating').displayName('Draconium Heavy Plating').texture('kubejs:item/heavy_plating/draconium_heavy_plating')
    sog.create('neutronium_heavy_plating').displayName('Neutronium Heavy Plating').texture('kubejs:item/heavy_plating/neutronium_heavy_plating')
    sog.create('infinity_heavy_plating').displayName('Infinity Heavy Plating').texture('kubejs:item/heavy_plating/infinity_heavy_plating')
    sog.create('chaos_heavy_plating').displayName('Chaotic Heavy Plating').texture('kubejs:item/heavy_plating/chaotic_heavy_plating')
    sog.create('californite_heavy_plating').displayName('Radioactive Heavy Plating').texture('kubejs:item/heavy_plating/irradiated_heavy_plating')
    sog.create('space_time_heavy_plating').displayName('SpaceTime Heavy Plating').texture('kubejs:item/heavy_plating/space_time_heavy_plating')
    sog.create('eternity_heavy_plating').displayName('Eternity Heavy Plating').texture('kubejs:item/heavy_plating/eternity_heavy_plating')
    // Power
        sog.create('tesla_coil_mk1').displayName('Tesla Coil MKI').texture('kubejs:item/power/tesla_coil_mk1').tooltip('Will produce 1A ZPM with the Tesla Tower')
    sog.create('tesla_coil_mk2').displayName('Tesla Coil MKII').texture('kubejs:item/power/tesla_coil_mk2').tooltip('Will produce 1A UEV with the Tesla Tower')
    sog.create('tesla_coil_mk3').displayName('Tesla Coil MKIII').texture('kubejs:item/power/tesla_coil_mk3').tooltip('Will produce 1A UXV with the Tesla Tower')
    // Particles
    sog.create('graviton').displayName('Graviton').texture('kubejs:item/particles/graviton')   
    sog.create('quarks').displayName('Quarks').texture('kubejs:item/particles/quarks')   
    sog.create('photon').displayName('Photon').texture('kubejs:item/particles/photon')   
    sog.create('strange_quarks').displayName('Strange Quarks').texture('kubejs:item/particles/strange_quarks')   
    sog.create('tau_neutrino').displayName('Tau Neutrino').texture('kubejs:item/particles/tau_neutrino')   
        sog.create('condensed_hydrogen_ball').displayName('Condensed Hydrogen Ball').texture('kubejs:item/particles/condensed_hydrogen_ball')
    sog.create('tachyon').displayName('Tachyon').texture('kubejs:item/particles/tachyon') 
    // Chaos
    sog.create('reactive_blend').displayName('Reactive Blend').texture('kubejs:item/chaos/reactive_blend')    
    sog.create('reactive_chaos_dust').displayName('Reactive Chaos Dust').texture('kubejs:item/chaos/reactive_chaos_dust')    
    sog.create('reactive_chaos_pellet').displayName('Reactive Chaos Pellet').texture('kubejs:item/chaos/reactive_chaos_pellet').tooltip('Produces 1 MAX+1 AMP on the Chaotic Singularity Reactor') 
    sog.create('infused_reactive_chaos_pellet').displayName('Infused Reactive Chaos Pellet').texture('kubejs:item/chaos/infused_reactive_chaos_pellet').tooltip('Produces 1 MAX+4 AMP on the Chaotic Singularity Reactor') 
    sog.create('reactive_chaos_waste').displayName('Reactive Chaos Waste').texture('kubejs:item/chaos/reactive_chaos_waste')    
    // UXV stuff
    sog.create('cosmic_circuit_board').maxStackSize(64).displayName('Cosmic Circuit Board')
    sog.create('cosmic_printed_circuit_board').maxStackSize(64).displayName('Cosmic Printed Circuit Board')
    // SMDs
    sog.create('complex_smd_capacitor').maxStackSize(64).displayName('Complex SMD Capacitor')
    sog.create('complex_smd_diode').maxStackSize(64).displayName('Complex SMD Diode')
    sog.create('complex_smd_inductor').maxStackSize(64).displayName('Complex SMD Inductor')
    sog.create('complex_smd_resistor').maxStackSize(64).displayName('Complex SMD Resistor')
    sog.create('complex_smd_transistor').maxStackSize(64).displayName('Complex SMD Transistor')
    // Nanites
    sog.create('cosmic_matter_nanites').maxStackSize(64).displayName('Cosmic Matter Nanites')
    sog.create('eternity_nanites').maxStackSize(64).displayName('Eternity Nanites')
    sog.create('stellar_matter_nanites').maxStackSize(64).displayName('Stellar Matter Nanites')
    sog.create('universium_nanites').maxStackSize(64).displayName('Universium Nanites')
    // Credits
    sog.create('atomically_compressed_neutronium_credit').maxStackSize(64).displayName('Atomically Compressed Neutronium Credit').texture('kubejs:item/atomically_compressed_neutronium_credit')
    // Exotic Condensate
    sog.create('quantum_stretched_lattice').maxStackSize(64).displayName('Quantum Stretched Lattice')
    sog.create('decay_particles').maxStackSize(64).displayName('Decay Particles')
    // Datas
    const data = ["cosmic", "elementary", "eternity", "plasma", "singularity", "spacetime", "universe"]
        data.forEach((data) => {
            sog.create(data + "_data")
                .displayName(data.toUpperCase() + " Data")
                .tooltip("§7Encrypted Data")
                .textureJson({ layer0: `kubejs:item/data/${data}_data` })
        })

//ERE
sog.create('watch_of_flowing_time')
    .displayName("Watch of Flowing Time")
    .texture('kubejs:item/watch_of_flowing_time')
    .tooltip("§5A tool to count every second in eternity")

sog.create('ultra_stable_cosmic_strings')
    .displayName("Ultra-Stable Cosmic Strings")
    .texture('kubejs:item/ultra_stable_cosmic_strings')
    .tooltip('Turns out string theory might be a bit more correct than we though')

sog.create('woven_space_time')
    .displayName("The Very Fabric of Reality")
    .texture('kubejs:item/woven_space_time')
    .tooltip('The line between sufficiently advanced science and magic is non-existant')

sog.create('entropic_cosmic_mesh')
    .displayName("Disordered Cosmic Strings")
    .texture('kubejs:item/entropic_cosmic_mesh')

    // PPF stuff
    sog.create('lv_circuit_etching_pattern')
        .displayName("LV Processor Pattern")
        .texture('kubejs:item/printed_lv_circuit')
    sog.create('mv_circuit_etching_pattern')
        .displayName("MV Processor Pattern")
        .texture('kubejs:item/printed_mv_circuit')
    sog.create('hv_circuit_etching_pattern')
        .displayName("HV Processor Pattern")
        .texture('kubejs:item/printed_hv_circuit')
    sog.create('ev_circuit_etching_pattern')
        .displayName("EV Processor Pattern")
        .texture('kubejs:item/printed_ev_circuit')
    sog.create('iv_circuit_etching_pattern')
        .displayName("IV Processor Pattern")
        .texture('kubejs:item/printed_iv_circuit')
    sog.create('luv_circuit_etching_pattern')
        .displayName("LuV Processor Pattern")
        .texture('kubejs:item/printed_luv_circuit')
    sog.create('zpm_circuit_etching_pattern')
        .displayName("ZPM Processor Pattern")
        .texture('kubejs:item/printed_zpm_circuit')
    sog.create('uv_circuit_etching_pattern')
        .displayName("UV Processor Pattern")
        .texture('kubejs:item/printed_uv_circuit')
    sog.create('uhv_circuit_etching_pattern')
        .displayName("UHV Processor Pattern")
        .texture('kubejs:item/printed_uhv_circuit')
    })

StartupEvents.registry('block', sog => {

    // C A S I N G S

    sog.create('neutronate_enriched_atomic_casing')
        .displayName('Neutronate Enriched Atomic Casing')
        .textureAll('kubejs:block/atomic/casing')
        .soundType('metal')
        .hardness(9)
        .requiresTool(true)
        .resistance(1)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('supercritical_neutronium_casing')
        .displayName('Supercritical Neutronium Casing')
        .textureAll('kubejs:block/neutronium/casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('neutronium_casing')
        .displayName('Neutronium Casing')
        .textureAll('kubejs:block/neutronium/ncasing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('kaemite_casing')
        .displayName('Kaemite Casing')
        .textureAll('kubejs:block/casings/kaemite_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('quantum_casing')
        .displayName('Quantum Casing')
        .textureAll('kubejs:block/casings/quantum_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('reinforced_computation_casing')
        .displayName('Reinforced Computation Casing')
        .textureAll('kubejs:block/casings/reinforced_computation_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('large_precision_casing')
        .displayName('Large Precision Casing')
        .textureAll('kubejs:block/casings/large_precision_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('component_tile_casing')
        .displayName('Component Tile Casing')
        .textureAll('kubejs:block/casings/component_tile_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('stellar_powered_casing')
        .displayName('Stellar Powered Casing')
        .textureAll('kubejs:block/casings/stellar_powered_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('highly_reinforced_radioactive_casing')
        .displayName('Highly Reinforced Radioactive Casing')
        .textureAll('kubejs:block/casings/highly_reinforced_radioactive_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('naquadria_turbine_casing')
        .displayName('Naquadria Turbine Casing')
        .textureAll('kubejs:block/casings/machine_casing_turbine_naquadria')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('osmiridium_pipe_casing')
        .displayName('Osmiridium Pipe Casing')
        .textureAll('kubejs:block/casings/machine_casing_pipe_osmiridium')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .lightLevel(0)
        .hardness(9)
        .tagBlock('forge:mineable/wrench')
    sog.create('superconductive_casing')
        .displayName('Superconductive Casing')
        .textureAll('kubejs:block/casings/superconductive_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .lightLevel(0)
        .hardness(9)
        .tagBlock('forge:mineable/wrench')
    sog.create('conductive_glass')
        .displayName('Conductive Glass')
        .textureAll('kubejs:block/casings/transparent/conductive_glass')
        .soundType('glass')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('high_power_casing')
        .displayName('High Power Maceration Casing')
        .textureAll('kubejs:block/casings/high_power_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('industrial_power_casing')
        .displayName('Industrial Power Casing')
        .textureAll('kubejs:block/casings/industrial_power_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('high_power_crushing_wheels')
        .displayName('High Power Crushing Wheels')
        .textureAll('kubejs:block/casings/high_power_crushing_wheels')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('highly_superconducting_coil_block')
        .displayName('Highly Superconducting Coil Block')
        .textureAll('kubejs:block/coils/machine_coil_highly_superconductor')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_casing')
        .displayName('Trascendental Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_shifter_casing')
        .displayName('Trascendental Shifter Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_sifter_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_reinforced_casing')
        .displayName('Trascendental Reinforced Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_reinforced_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_space_time_casing')
        .displayName('Transcendental SpaceTime Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_space_time_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_resonant_casing')
        .displayName('Trascendental Resonant Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_resonant_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_neutronic_casing')
        .displayName('Trascendental Neutronic Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_neutronic_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_draconic_casing')
        .displayName('Trascendental Draconic Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_draconic_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('trascendental_cosmic_casing')
        .displayName('Trascendental Cosmic Casing')
        .textureAll('kubejs:block/casings/endgame/trascendental_cosmic_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('chemical_tier_one')
        .displayName('Chemical Tier 1')
        .textureAll('kubejs:block/casings/tiered/chemical_tier_one')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('chemical_tier_two')
        .displayName('Chemical Tier 2')
        .textureAll('kubejs:block/casings/tiered/chemical_tier_two')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('chemical_tier_three')
        .displayName('Chemical Tier 3')
        .textureAll('kubejs:block/casings/tiered/chemical_tier_three')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('chemical_tier_four')
        .displayName('Chemical Tier 4')
        .textureAll('kubejs:block/casings/tiered/chemical_tier_four')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('chemical_tier_five')
        .displayName('Chemical Tier 5')
        .textureAll('kubejs:block/casings/tiered/chemical_tier_five')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('chemical_tier_six')
        .displayName('Chemical Tier 6')
        .textureAll('kubejs:block/casings/tiered/chemical_tier_six')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('asteroid_belt_marker')
        .displayName('Asteroid Belt')
        .textureAll('kubejs:block/asteroid_belt')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('eternity_casing')
        .displayName('Eternity Casing')
        .textureAll('kubejs:block/casings/eternity_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('semi_stable_casing')
        .displayName('Semi-Stable Casing')
        .textureAll('kubejs:block/casings/semi_stable_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('cryogenic_casing')
        .displayName('Cryogenic Casing')
        .textureAll('kubejs:block/casings/cryogenic_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('advanced_air_intake_hatch')
        .displayName('Advanced Air Intake Hatch')
        .textureAll('kubejs:block/casings/advanced_air_intake_hatch')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('kevlar_casing')
        .displayName('Kevlar Casing')
        .textureAll('kubejs:block/casings/kevlar_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('atomic_alloy_plated_glass')
        .displayName('Atomic Alloy Plated Glass')
        .textureAll('kubejs:block/casings/transparent/atomic_alloy_plated_glass')
        .soundType('glass')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('peek_reinforced_glass')
        .displayName('PEEK Reinforced Glass')
        .textureAll('kubejs:block/casings/transparent/peek_reinforced_glass')
        .soundType('glass')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('peek_plated_heat_resisted_casing')
        .displayName('PEEK Plated Heat Resistent Casing')
        .textureAll('kubejs:block/casings/peek_plated_heat_resisted_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('machine_casing_inert_peek')
        .displayName('Inert PEEK Casing')
        .textureAll('kubejs:block/casings/machine_casing_inert_peek')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('machine_casing_pipe_peek')
        .displayName('PEEK Pipe Casing')
        .textureAll('kubejs:block/casings/machine_casing_pipe_peek')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('ultimate_engine_intake_casing', 'gtceu:active')
        .simple('kubejs:block/casings/machine_casing_ultimate_engine_intake')
        .displayName('Ultimate Engine Intake Casing')
        .soundType('metal')
        .resistance(6)
        .requiresTool(true)
        .hardness(5)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock("forge:mineable/wrench")
    sog.create('ultra_reflective_laser_cooling_casing')
        .displayName('Ultra Reflective Laser Cooling Casing')
        .textureAll('kubejs:block/casings/ultra_reflective_laser_cooling_casing')
        .soundType('metal')
        .resistance(6)
        .requiresTool(true)
        .hardness(5)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock("forge:mineable/wrench")

// F U S I O N
    sog.create('fusion_casing_mk4')
        .displayName('Fusion Machine Casing MK IV')
        .textureAll('kubejs:block/fusion/fusion_casing_mk4')
        .soundType('metal')
        .resistance(1)
        .hardness(9)
        .requiresTool(true)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('fusion_coil_mk2')
        .displayName('Fusion Coil Block MK II')
        .textureAll('kubejs:block/fusion/fusion_coil_mk2')
        .soundType('metal')
        .resistance(1)
        .hardness(9)
        .requiresTool(true)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('fusion_glass_mk2')
        .displayName('Reinforced Fusion Glass')
        .textureAll('kubejs:block/fusion/fusion_glass_mk2')
        .soundType('glass')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')

    sog.create('fusion_machine_casing_mk_v')
        .displayName('Fusion Machine Casing MK V')
        .textureAll('kubejs:block/fusion/fusion_machine_casing_mk_v')
        .soundType('metal')
        .hardness(9)
        .requiresTool(true)
        .resistance(1)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('fusion_coil_block_mk_3')
        .displayName('Fusion Coil Block MK III')
        .textureAll('kubejs:block/fusion/fusion_coil_block_mk_3')
        .soundType('metal')
        .hardness(9)
        .requiresTool(true)
        .resistance(1)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')        
    sog.create('eternity_fusion_machine_casing')
        .displayName('Eternity Fusion Machine Casing')
        .textureAll('kubejs:block/fusion/eternity_fusion_machine_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('eternity_fusion_coil_block')
        .displayName('Eternity Fusion Coil Block')
        .textureAll('kubejs:block/fusion/eternity_fusion_coil_block')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')

    // P R O J E C T O R   M O D U L E S
    
    sog.create('drilling_projector_module')
        .displayName('Space Drill Projector Module')
        .textureAll('kubejs:block/projector/drilling_projector_module')
        .soundType('metal')
        .resistance(1)
        .hardness(9)
        .requiresTool(true)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('pumping_projector_module')
        .displayName('Space Pump Projector Module')
        .textureAll('kubejs:block/projector/pumping_projector_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('cosmic_projector_module')
        .displayName('Cosmic Projector Module')
        .textureAll('kubejs:block/projector/cosmic_projector_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('fusion_projector_module')
        .displayName('Fusion Projector Module')
        .textureAll('kubejs:block/projector/fusion_projector_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('dimensional_pump_module')
        .displayName('Dimensional Pump Module')
        .textureAll('kubejs:block/casings/tiered/dimensional_pump_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
        // C O I L S
    sog.create('atomic_alloy_coil_block', 'gtceu:coil')
        .temperature(12500)
        .level(32) //this is the multismelter parallel amount. The math is parallel = (level * 32)
        .energyDiscount(32) // this is the energy discount theres some esoteric math behind it but if you match it with level it will be fine
        .tier(9) //This is the cracker and pyrolyse oven stat. pyrolyse is 50% * (tier + 1). Cracker is -10% * (tier + 1)
        .textureAll('kubejs:block/atomic/coil')
        .hardness(5)
        .requiresTool(true)
        .soundType('metal')
        .tagBlock('forge:mineable/wrench')
    sog.create('resonant_essence_coil_block', 'gtceu:coil')
        .temperature(13500)
        .level(64)
        .energyDiscount(64) // 
        .tier(10)
        .textureAll('kubejs:block/coils/machine_coil_resonant_essence')
        .hardness(5)
        .requiresTool(true)
        .soundType('metal')
        .tagBlock('forge:mineable/wrench')
    sog.create('awakened_draconium_coil_block', 'gtceu:coil')
        .temperature(15500)
        .level(128)
        .energyDiscount(128) // 
        .tier(11)
        .coilMaterial(() => GTMaterials.get('awakened_draconium'))
        .textureAll('kubejs:block/coils/machine_coil_awakened_draconium')
        .hardness(5)
        .requiresTool(true)
        .soundType('metal')
        .tagBlock('forge:mineable/wrench')
    sog.create('infinity_coil_block', 'gtceu:coil')
        .temperature(17950)
        .level(1024)
        .energyDiscount(1024) // 
        .tier(12)
        .coilMaterial(() => GTMaterials.get('infinity'))
        .textureAll('kubejs:block/coils/machine_coil_infinity')
        .hardness(5)
        .requiresTool(true)
        .soundType('metal')
        .tagBlock('forge:mineable/wrench')
    sog.create('chrono-infinity_alloy_coil_block', 'gtceu:coil')
        .temperature(19590)
        .level(2048)
        .energyDiscount(2048) // 
        .tier(99)
        .coilMaterial(() => GTMaterials.get('chrono-infinity'))
        .textureAll('kubejs:block/coils/machine_coil_chrono-infinity_alloy')
        .hardness(5)
        .requiresTool(true)
        .soundType('metal')
        .tagBlock('forge:mineable/wrench')
          // Compressed TNT
    sog.create('compressed_industrial_tnt')
        .displayName('Compressed Industrial TNT')
        .textureAll('kubejs:block/compressed_tnt/compressed_industrial_tnt')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/axe')
    sog.create('double_compressed_industrial_tnt')
        .displayName('Double Compressed Industrial TNT')
        .textureAll('kubejs:block/compressed_tnt/double_compressed_industrial_tnt')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/axe')
    sog.create('triple_compressed_industrial_tnt')
        .displayName('Triple Compressed Industrial TNT')
        .textureAll('kubejs:block/compressed_tnt/triple_compressed_industrial_tnt')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/axe')
    sog.create('adv_high_power_crushing_wheels')
        .displayName('Advanced High Power Crusher Wheels')
        .textureAll('kubejs:block/casings/adv_high_power_crushing_wheels')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock('forge:mineable/wrench')
    sog.create('orbital_space_containment_casing')
        .displayName('Orbital Space Containment Casing')
        .textureAll('kubejs:block/casings/orbital_space_containment_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('orbital_solar_casing', 'gtceu:active')
        .simple('kubejs:block/casings/orbital_solar_casing')
        .displayName('Orbital Solar Casing')
        .soundType('metal')
        .resistance(6)
        .requiresTool(true)
        .hardness(5)
        .lightLevel(0)
        .defaultCutout()
        .tagBlock("forge:mineable/wrench")
    sog.create('dimensional_orbital_mining_module')
        .displayName('Dimensional Orbital Mining Module')
        .textureAll('kubejs:block/orbital_bore/dimensional_orbital_mining_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('dimensional_orbital_pumping_module')
        .displayName('Dimensional Orbital Pumping Module')
        .textureAll('kubejs:block/orbital_bore/dimensional_orbital_pumping_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('dimensional_orbital_fusion_module')
        .displayName('Dimensional Orbital Fusion Module')
        .textureAll('kubejs:block/orbital_bore/dimensional_orbital_fusion_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('orbital_pipe_casing')
        .displayName('Orbital Pipe Casing')
        .textureAll('kubejs:block/casings/orbital_pipe_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('space_resistant_orbital_casing')
        .displayName('Space-Resistant Orbital Casing')
        .textureAll('kubejs:block/casings/space_resistant_orbital_casing')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('interstellar_mining_module')
        .displayName('Interstellar Mining Module')
        .textureAll('kubejs:block/orbital_bore/interstellar_mining_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('interstellar_pumping_module')
        .displayName('Interstellar Pumping Module')
        .textureAll('kubejs:block/orbital_bore/interstellar_pumping_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')
    sog.create('interstellar_fusion_module')
        .displayName('Interstellar Fusion Module')
        .textureAll('kubejs:block/orbital_bore/interstellar_fusion_module')
        .soundType('metal')
        .resistance(1)
        .requiresTool(true)
        .hardness(9)
        .lightLevel(0)
        .tagBlock('forge:mineable/wrench')      
})
