ServerEvents.recipes(event => {



        
        //Plasmas
        
    event.recipes.gtceu.naquadahmk1('naquadriaplasma')
        .inputFluids('gtceu:pure_naquadria_fuel 5000', 'gtceu:helium_plasma 1500', 'gtceu:depleted_thorium_fuel 15000')
        .outputFluids('gtceu:naquadria_plasma_plasma 5000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UV]))
    event.recipes.gtceu.naquadahmk1('thoriumplasma')
        .inputFluids('gtceu:condensed_star_matter 5000', 'gtceu:naquadria_plasma_plasma 5000', 'gtceu:depleted_thorium_fuel 30000')
        .outputFluids('gtceu:thorium_plasma_plasma 10000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UHV]))
    event.recipes.gtceu.naquadahmk1('naquadriaplasmamk2')
        .inputFluids('gtceu:naquadria_fuel_mk2 5000', 'gtceu:thorium_plasma_plasma 5000', 'gtceu:stabilized_enriched_thorium_fuel 15000')
        .outputFluids('gtceu:naquadria_plasma_mk2_plasma 5000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UHV]))
    event.recipes.gtceu.naquadahmk2('thoriumplasma')
        .inputFluids('gtceu:naquadria 15000', 'gtceu:americium_plasma 5000', 'gtceu:stabilized_enriched_thorium_fuel 30000')
        .outputFluids('gtceu:thorium_plasma_plasma 20000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UHV]))
    event.recipes.gtceu.naquadahmk2('naquadriaplasmamk2')
        .inputFluids('gtceu:naquadria_fuel_mk2 5000', 'gtceu:thorium_plasma_plasma 7500', 'gtceu:stabilized_enriched_thorium_fuel 30000')
        .outputFluids('gtceu:naquadria_plasma_mk2_plasma 10000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UEV]))
    event.recipes.gtceu.naquadahmk2('naquadriaplasmamk3')
        .inputFluids('gtceu:naquadria_fuel_mk3 5000', 'gtceu:naquadria_plasma_mk2_plasma 5000', 'gtceu:meta_stable_hyper_enriched_thorium_fuel 30000')
        .outputFluids('gtceu:naquadria_plasma_mk3_plasma 10000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UEV]))
        
        //Thorium Fuel Line
        

    event.recipes.gtceu.extreme_cracking_unit('lightlyplasmacrackedunstableenrichedthoriumfuel')
       .inputFluids('gtceu:unstable_enriched_thorium_fuel 30000', 'gtceu:argon_plasma 5000')
	   .chancedInput('2x gtceu:neutron_reflector', 3333, 0)
       .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
       .chancedInput('2x gtceu:neutron_reflector', 1111, 0)
       .outputFluids('gtceu:lightly_plasmacracked_unstable_enriched_thorium_fuel 15000')
       .duration(200)
       .EUt((GTValues.VA[GTValues.UV]))
    event.recipes.gtceu.extreme_cracking_unit('severlyplasmacrackedunstableenrichedthoriumfuel')
       .inputFluids('gtceu:unstable_enriched_thorium_fuel 30000', 'gtceu:iron_plasma 5000')
       .chancedInput('2x gtceu:neutron_reflector', 5000, 0)
       .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
       .chancedInput('2x gtceu:neutron_reflector', 1250, 0)
       .outputFluids('gtceu:severly_plasmacracked_unstable_enriched_thorium_fuel 15000')
       .duration(400)
       .EUt((GTValues.VA[GTValues.UHV]))
  
    event.recipes.gtceu.vacuum_freezer('lqnitrogen')
       .inputFluids('gtceu:nitrogen 1000')
       .outputFluids('gtceu:liquid_nitrogen 1000')
       .duration(2400)
       .EUt((GTValues.VA[GTValues.LuV]))
    event.recipes.gtceu.vacuum_freezer('stabilizedenrichedthoriumfuel')
       .inputFluids('gtceu:hot_stabilized_enriched_thorium_fuel 10000','gtceu:liquid_nitrogen 10000')
       .outputFluids('gtceu:stabilized_enriched_thorium_fuel 10000')
       .duration(2400)
       .EUt((GTValues.VA[GTValues.UV]))
    event.recipes.gtceu.atomiccompressor('sdhog')
        .chancedInput('kubejs:quantum_energy_capsule', 2500, 0)
        .inputFluids('gtceu:high_octane_gasoline 150000')
        .outputFluids('gtceu:super_dense_hog 15000')
        .duration(500)
        .EUt(GTValues.VA[GTValues.UHV]);

     event.recipes.gtceu.chemical_plant('hotmetastablehyperenrichedthoriumfuel')
        .notConsumable('kubejs:chemical_tier_four')
        .inputFluids('gtceu:very_unstable_hyper_enriched_thorium_fuel 20000','gtceu:hypoxylon 10000', 'gtceu:neutronium 5000')
        .outputFluids('gtceu:hot_meta_stable_hyper_enriched_thorium_fuel 20000')
        .circuit(20)
        .duration(50*20)
        .EUt(GTValues.VA[GTValues.UEV])
     event.recipes.gtceu.vacuum_freezer('metastablehyperenrichedthoriumfuel')
       .inputFluids('gtceu:hot_meta_stable_hyper_enriched_thorium_fuel 10000','gtceu:liquid_nitrogen 10000')
       .outputFluids('gtceu:meta_stable_hyper_enriched_thorium_fuel 10000')
       .duration(2400)
       .EUt((GTValues.VA[GTValues.UHV]))
       
        //Naquadria Fuel Line
        

    event.recipes.gtceu.extreme_cracking_unit('lightlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:enriched_naquadria_fuel_base 20000', 'gtceu:oxygen_plasma 5000')
       .chancedInput('2x gtceu:neutron_reflector', 3333, 0)
       .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
       .chancedInput('2x gtceu:neutron_reflector', 1111, 0)
       .outputFluids('gtceu:lightly_plasmacracked_enriched_naquadria_fuel_base 10000')
       .duration(200)
       .EUt((GTValues.VA[GTValues.UHV]))
    event.recipes.gtceu.extreme_cracking_unit('severlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:enriched_naquadria_fuel_base 20000', 'gtceu:nickel_plasma 5000')
       .chancedInput('2x gtceu:neutron_reflector', 5000, 0)
       .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
       .chancedInput('2x gtceu:neutron_reflector', 1250, 0)
       .outputFluids('gtceu:severly_plasmacracked_enriched_naquadria_fuel_base 10000')
       .duration(400)
       .EUt((GTValues.VA[GTValues.UEV]))
    event.recipes.gtceu.distillation_tower('lightlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:lightly_plasmacracked_enriched_naquadria_fuel_base 1000')
       .outputFluids('gtceu:heavy_naquadria_fuel_waste 100', 'gtceu:heavy_naquadria_fuel 200', 'gtceu:light_naquadria_fuel_waste 100','gtceu:light_naquadria_fuel 500' ,'gtceu:enriched_naquadah_fuel_waste 100')
       .cleanroom(CleanroomType.CLEANROOM)
       .duration(200)
       .EUt((GTValues.VA[GTValues.UV]))
    event.recipes.gtceu.distillation_tower('severlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:severly_plasmacracked_enriched_naquadria_fuel_base 1000')
       .outputFluids('gtceu:super_dense_naquadria_fuel 200', 'gtceu:heavy_naquadria_fuel_waste 100','gtceu:heavy_naquadria_fuel 500', 'gtceu:light_naquadria_fuel_waste 100' )
       .cleanroom(CleanroomType.CLEANROOM)
       .duration(200)
       .EUt((GTValues.VA[GTValues.UV]))


     event.recipes.gtceu.chemical_plant('naquadriafuelmixturemk2')
        .notConsumable('kubejs:chemical_tier_three')
        .inputFluids('gtceu:treated_light_naquadria_fuel 36000','gtceu:treated_heavy_naquadria_fuel 18000', 'gtceu:neutronium 1000', 'gtceu:enriched_naquadria_fuel_base 5000')
        .outputFluids('gtceu:naquadria_fuel_mixture_mk2 60000')
        .circuit(21)
        .duration(50*20)
        .EUt(GTValues.VA[GTValues.UHV])
     event.recipes.gtceu.chemical_plant('naquadriafuelmixturemk3')
        .notConsumable('kubejs:chemical_tier_four')
        .inputFluids('gtceu:treated_light_naquadria_fuel 36000','gtceu:treated_heavy_naquadria_fuel 54000', 'gtceu:treated_super_dense_naquadria_fuel 30000', 'gtceu:enriched_naquadria_fuel_base 30000')
        .outputFluids('gtceu:naquadria_fuel_mixture_mk3 150000')
        .circuit(21)
        .duration(50*20)
        .EUt(GTValues.VA[GTValues.UEV])
   event.recipes.gtceu.atomiccompressor('naquadriafuelmk2')
        .chancedInput('kubejs:quantum_energy_capsule', 2500, 0)
        .inputFluids('gtceu:naquadria_fuel_mixture_mk2 60000')
        .outputFluids('gtceu:naquadria_fuel_mk2 10000')
        .duration(500)
        .EUt(GTValues.VA[GTValues.UHV]);
   event.recipes.gtceu.atomiccompressor('naquadriafuelmk3')
        .chancedInput('kubejs:quantum_energy_capsule', 2500, 0)
        .inputFluids('gtceu:naquadria_fuel_mixture_mk3 150000')
        .outputFluids('gtceu:naquadria_fuel_mk3 20000')
        .duration(500)
        .EUt(GTValues.VA[GTValues.UEV]);
        
        //Fuel Wastes


})