GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('draconium_assembly_line', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('assembly_line')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock('kubejs:draconic_assembly_line_grating'))
        .pattern(definition => FactoryBlockPattern.start()      
            .aisle("BBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDDD", "AAAAAAAAAAAAAAAAA")
            .aisle("BBBBBBBBBBBBBBBBB", "FFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGG", "FFFFFFFFFFFFFFFFF", "HHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIII")
            .aisle("BBBBBBBBBBBBBBBBB", "GGGGGGGGGGGGGGGGG", "JJJJJJJJJJJJJJJJJ", "GGGGGGGGGGGGGGGGG", "HHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIII")
            .aisle("BBBBBBBBBBBBBBBBB", "FFFFFFFFFFFFFFFFF", "GGGGGGGGGGGGGGGGG", "FFFFFFFFFFFFFFFFF", "HHHHHHHHHHHHHHHHH", "IIIIIIIIIIIIIIIII")
            .aisle("BBBBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCC", "CCCCCCCCCCCCCCCCC", "DDDDDDDDDDDDDDDLK", "AAAAAAAAAAAAAAAAA")
                .where("K", Predicates.controller(Predicates.blocks(definition.get())))
                .where("A", Predicates.any())
                .where("C", Predicates.blocks("kubejs:fusion_glass_mk2"))
                .where("B", Predicates.blocks("kubejs:quantum_casing"))
                .where("F", Predicates.blocks("kubejs:draconic_assembly_control_casing"))
                .where("G", Predicates.blocks("gtceu:electrolytic_cell"))
                .where("H", Predicates.blocks("kubejs:draconic_assembly_line_casing"))
                .where("I", Predicates.blocks("kubejs:draconium_machine_casing"))
                .where("J", Predicates.blocks("kubejs:fusion_coil_mk2"))
                .where("D", Predicates.blocks("kubejs:draconic_assembly_line_grating")
                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS, PartAbility.IMPORT_ITEMS, PartAbility.EXPORT_FLUIDS, PartAbility.IMPORT_FLUIDS))
                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1))
                    )
                .where("L", Predicates.blocks("kubejs:draconic_assembly_line_grating")
                    .or(Predicates.blocks("gtceu:iv_parallel_hatch"))
                    .or(Predicates.blocks("gtceu:luv_parallel_hatch"))
                    .or(Predicates.blocks("gtceu:zpm_parallel_hatch"))
                    )
            .build()
        )
        .workableCasingModel("kubejs:block/casings/draconic_assembly_line_grating", 'gtceu:block/multiblock/assembly_line')
})