GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('particle_implosion_chamber', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('implosion_compressor')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.MACHINE_CASING_UHV)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('AAAAA', 'AAAAA', 'AAAAA', 'AAAAA', 'AAAAA')
            .aisle('AAAAA', 'ABBBA', 'ABBBA', 'ABBBA', 'AAAAA')
            .aisle('AAAAA', 'A###A', 'A###A', 'A###A', 'AAAAA')
            .aisle('AAOAA', 'CCCCC', 'CCCCC', 'CCCCC', 'AAAAA')
                .where('O', Predicates.controller(Predicates.blocks(definition.get())))
                .where('#', Predicates.any())
                .where('B', Predicates.blocks('gtceu:titanium_firebox_casing'))
                .where('C', Predicates.blocks('kubejs:atomic_alloy_plated_glass'))
                .where('A', Predicates.blocks("gtceu:atomic_casing")
                    .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                    .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                )
    )
    .workableCasingModel("gtceu:block/casings/gcym/atomic_casing", 'gtceu:block/multiblock/implosion_compressor')
    })