ServerEvents.recipes(sog => {
// C A S I N G S   A N D   B L O C K S



// Fusion MK 4 Recipes
        sog.recipes.gtceu.fusion_reactor('neon_plasma')
                .inputFluids('gtceu:neon 144', 'gtceu:argon_plasma 16')
                .outputFluids('gtceu:neon_plasma_plasma 64')
                .fusionStartEU(640000000)
                .duration(60*4)
                .EUt((GTValues.VA[GTValues.UEV]))
        sog.recipes.gtceu.fusion_reactor('crystal_matrix')
                .inputFluids('gtceu:diamond 4320', 'gtceu:radon 2160')
                .outputFluids('gtceu:crystal_matrix 2160')
                .fusionStartEU(640000000)
                .EUt((GTValues.VA[GTValues.UEV]))
                .totalCWU(64*5)
                .CWUt(64)
        sog.recipes.gtceu.fusion_reactor('cosmic_titanium')
                .inputFluids('gtceu:titanium 5250', 'gtceu:resonant_essence 240')
                .outputFluids('gtceu:cosmic_titanium 480')
                .fusionStartEU(640000000)
                .EUt((GTValues.VA[GTValues.UEV]))
                .totalCWU(64*5)
                .CWUt(64)
        sog.recipes.gtceu.fusion_reactor('cosmic_tungsten')
                .inputFluids('gtceu:tungsten 5250', 'gtceu:resonant_essence 240')
                .outputFluids('gtceu:cosmic_tungsten 480')
                .fusionStartEU(640000000)
                .EUt((GTValues.VA[GTValues.UEV]))
                .totalCWU(64*5)
                .CWUt(64)
        sog.recipes.gtceu.fusion_reactor('cosmic_iridium')
                .inputFluids('gtceu:stabilized_iridium 5250', 'gtceu:resonant_essence 240')
                .outputFluids('gtceu:cosmic_iridium 480')
                .fusionStartEU(640000000)
                .EUt((GTValues.VA[GTValues.UEV]))
                .totalCWU(64*5)
                .CWUt(96)
        sog.recipes.gtceu.fusion_reactor('cosmic_osmium')
                .inputFluids('gtceu:osmium 5325', 'gtceu:resonant_essence 240')
                .outputFluids('gtceu:cosmic_osmium 480')
                .fusionStartEU(640000000)
                .EUt((GTValues.VA[GTValues.UEV]))
                .totalCWU(64*5)
                .CWUt(64)
        sog.recipes.gtceu.fusion_reactor('nihonium')
                .inputFluids('gtceu:zinc 3825', 'gtceu:bismuth 1800')
                .outputFluids('gtceu:nihonium 3840')
                .fusionStartEU(640000000)
                .EUt((GTValues.VA[GTValues.UEV]))
                .totalCWU(256*5)
                .CWUt(256)
        sog.recipes.gtceu.fusion_reactor('oganesson')
                .inputFluids('gtceu:californium 3825', 'gtceu:cosmic_iridium 525')
                .outputFluids('gtceu:oganesson 3840')
                .fusionStartEU(640000000)
                .EUt((GTValues.VA[GTValues.UEV]))
                .totalCWU(256*5)
                .CWUt(256)
})
