GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('hyper_component_assembling')
        .category('multiblocks')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 9, 0) // Item Input, Output, Fluid Input, Output
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('hyper_assembly_line', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(['hyper_component_assembling', 'assembly_line'])
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock('kubejs:draconic_assembly_line_grating'))
        .pattern(definition => FactoryBlockPattern.start()
                        .aisle("BBBBBBBBBBBBBBBBB", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "EEEEEEEEEEEEEEEEE", "AAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAA")
            .aisle("BBBBBBBBBBBBBBBBB", "GGGGGGGGGGGGGGGGG", "GHHHHHHHHHHHHHHHG", "GGGGGGGGGGGGGGGGG", "GHHHHHHHHHHHHHHHG", "GGGGGGGGGGGGGGGGG", "EIIIIIIIIIIIIIIIE", "BBBBBBBBBBBBBBBBB", "AAAAAAAAAAAAAAAAA")
            .aisle("BBBBBBBBBBBBBBBBB", "GJJJJJJJJJJJJJJJG", "KLLLLLLLLLLLLLLLK", "KLLLLLLLLLLLLLLLK", "KLLLLLLLLLLLLLLLK", "GJJJJJJJJJJJJJJJG", "EIIIIIIIIIIIIIIIE", "BLLLLLLLLLLLLLLLB", "ABBBBBBBBBBBBBBBA")
            .aisle("BBBBBBBBBBBBBBBBB", "GJJJJJJJJJJJJJJJG", "KLLLLLLLLLLLLLLLK", "KKKKKKKKKKKKKKKKK", "KLLLLLLLLLLLLLLLK", "GJJJJJJJJJJJJJJJG", "EIIIIIIIIIIIIIIIE", "BLLLLLLLLLLLLLLLB", "ABBBBBBBBBBBBBBBA")
            .aisle("BBBBBBBBBBBBBBBBB", "GJJJJJJJJJJJJJJJG", "KLLLLLLLLLLLLLLLK", "KLLLLLLLLLLLLLLLK", "KLLLLLLLLLLLLLLLK", "GJJJJJJJJJJJJJJJG", "EIIIIIIIIIIIIIIIE", "BLLLLLLLLLLLLLLLB", "ABBBBBBBBBBBBBBBA")
            .aisle("BBBBBBBBBBBBBBBBB", "GGGGGGGGGGGGGGGGG", "GHHHHHHHHHHHHHHHG", "GGGGGGGGGGGGGGGGG", "GHHHHHHHHHHHHHHHG", "GGGGGGGGGGGGGGGGG", "EIIIIIIIIIIIIIIIE", "BBBBBBBBBBBBBBBBB", "AAAAAAAAAAAAAAAAA")
            .aisle("BBBBBBBBBBBBBBBBB", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "CDDDDDDDDDDDDDDDC", "EEEEEEEEEEEEEEEEM", "AAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAA")
                .where("M", Predicates.controller(Predicates.blocks(definition.get())))
                .where("A", Predicates.any())
                .where("B", Predicates.blocks("kubejs:semi_stable_casing"))
                .where("C", Predicates.blocks("gtceu:pure_cosmic_matter_frame"))
                .where("D", Predicates.blocks("kubejs:atomic_alloy_plated_glass"))
                .where("G", Predicates.blocks("kubejs:eternity_assembly_control_casing"))
                .where("H", Predicates.blocks("gtceu:electrolytic_cell"))
                .where("I", Predicates.blocks("gtceu:assembly_line_casing"))
                .where("J", Predicates.blocks("gtceu:eternity_block"))
                .where("K", Predicates.blocks("kubejs:awakened_draconium_coil_block"))
                .where("L", Predicates.blocks("kubejs:fusion_coil_block_mk_3"))
                .where("E", Predicates.blocks("kubejs:draconic_assembly_line_grating")
                    .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                    .or(Predicates.abilities(PartAbility.MAINTENANCE))
                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS, PartAbility.EXPORT_FLUIDS, PartAbility.IMPORT_ITEMS, PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_LASER, PartAbility.INPUT_ENERGY, PartAbility.PARALLEL_HATCH))
                    )
            .build()
        )
        .workableCasingModel("kubejs:block/casings/draconic_assembly_line_grating", 'gtceu:block/multiblock/assembly_line')
})
