GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('singularity_reactor')
        .category('generator')
        .setEUIO('out')
        .setMaxIOSize(0, 0, 2, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.REPLICATOR)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('singularity_reactor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .generator(true)
        .recipeType('singularity_reactor')
        .noRecipeModifier()
        .regressWhenWaiting(false)
        .appearanceBlock(() => Block.getBlock('soggtaddon:quantum_field_stabilization_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('####CCC####', '###########', '###########', '###########', '###########', '###########', '###########', '###########', '###########', '###########', '####CCC####', )
            .aisle('##CCCCCCC##', '####B#B####', '####B#B####', '###########', '###########', '###########', '###########', '###########', '####B#B####', '####B#B####', '##CCCCCCC##', )
            .aisle('#CCCCCCCCC#', '##B#####B##', '##B#####B##', '##B#####B##', '##B#####B##', '##B#BBB#B##', '##B#####B##', '##B#####B##', '##B#####B##', '##B#####B##', '#CCCCCCCCC#', )
            .aisle('#CCCCCCCCC#', '####BBB####', '####AAA####', '####AAA####', '####AAA####', '###BAAAB###', '####AAA####', '####AAA####', '####AAA####', '####BBB####', '#CCCCCCCCC#', )
            .aisle('CCCCCCCCCCC', '#B#B###B#B#', '#B#A###A#B#', '###A###A###', '###A###A###', '##BA###AB##', '###A###A###', '###A###A###', '#B#A###A#B#', '#B#B###B#B#', 'CCCCCCCCCCC', )
            .aisle('CCCCCCCCCCC', '###B###B###', '###A###A###', '###A###A###', '###A###A###', '##BA###AB##', '###A###A###', '###A###A###', '###A###A###', '###B###B###', 'CCCCCYCCCCC', )
            .aisle('CCCCCCCCCCC', '#B#B###B#B#', '#B#A###A#B#', '###A###A###', '###A###A###', '##BA###AB##', '###A###A###', '###A###A###', '#B#A###A#B#', '#B#B###B#B#', 'CCCCCCCCCCC', )
            .aisle('#CCCCCCCCC#', '####BBB####', '####AAA####', '####AAA####', '####AAA####', '###BAAAB###', '####AAA####', '####AAA####', '####AAA####', '####BBB####', '#CCCCCCCCC#', )
            .aisle('#CCCCCCCCC#', '##B#####B##', '##B#####B##', '##B#####B##', '##B#####B##', '##B#BBB#B##', '##B#####B##', '##B#####B##', '##B#####B##', '##B#####B##', '#CCCCCCCCC#', )
            .aisle('##CCCCCCC##', '####B#B####', '####B#B####', '###########', '###########', '###########', '###########', '###########', '####B#B####', '####B#B####', '##CCCCCCC##', )
            .aisle('####CKC####', '###########', '###########', '###########', '###########', '###########', '###########', '###########', '###########', '###########', '####CCC####', )
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('#', Predicates.any())
                .where('A', Predicates.blocks('soggtaddon:ultra_dense_collider_casing'))
                .where('B', Predicates.blocks('soggtaddon:high_energy_collider_casing'))
                .where("C", Predicates.blocks('soggtaddon:quantum_field_stabilization_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                )
                .where('Y', Predicates.abilities(PartAbility.OUTPUT_ENERGY)
                    .or(Predicates.abilities(PartAbility.SUBSTATION_OUTPUT_ENERGY))
                    .or(Predicates.abilities(PartAbility.OUTPUT_LASER))
                )
            .build()
        )
        .workableCasingModel("soggtaddon:block/casings/quantum_field_stabilization_casing", 'gtceu:block/multiblock/generator/large_plasma_turbine')
    })