GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('fusion_mk5')
        .category('multiblocks')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 1) // Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.REPLICATOR)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('fusion_mk5', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('fusion_mk5')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock('kubejs:fusion_machine_casing_mk_v'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("AAAAAAAAAAAAAAAAAAAAA", "AAAAAAABBBBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAAAA")
            .aisle("AAAAAAABBBBBBBAAAAAAA", "AAAAABBDDDDDDDBBAAAAA", "AAAAAAABBBBBBBAAAAAAA")
            .aisle("AAAAABBAAAAAAABBAAAAA", "AAAABDDBBBEBBBDDBAAAA", "AAAAABBAAAAAAABBAAAAA")
            .aisle("AAAABAAAAAAAAAAABAAAA", "AAABDBBAAAAAAABBDBAAA", "AAAABAAAAAAAAAAABAAAA")
            .aisle("AAABAAAAAAAAAAAAABAAA", "AABDBAAAAAAAAAAABDBAA", "AAABAAAAAAAAAAAAABAAA")
            .aisle("AABAAAAAAAAAAAAAAABAA", "ABDBAAAAAAAAAAAAABDBA", "AABAAAAAAAAAAAAAAABAA")
            .aisle("AABAAAAAAAAAAAAAAABAA", "ABDBAAAAAAAAAAAAABDBA", "AABAAAAAAAAAAAAAAABAA")
            .aisle("ABAAAAAAAAAAAAAAAAABA", "BDBAAAAAAAAAAAAAAABDB", "ABAAAAAAAAAAAAAAAAABA")
            .aisle("ABAAAAAAAAAAAAAAAAABA", "BDBAAAAAAAAAAAAAAABDB", "ABAAAAAAAAAAAAAAAAABA")
            .aisle("ABAAAAAAAAAAAAAAAAABA", "BDBAAAAAAAAAAAAAAABDB", "ABAAAAAAAAAAAAAAAAABA")
            .aisle("ABAAAAAAAAAAAAAAAAABA", "BDBAAAAAAAAAAAAAAABDB", "ABAAAAAAAAAAAAAAAAABA")
            .aisle("ABAAAAAAAAAAAAAAAAABA", "BDBAAAAAAAAAAAAAAABDB", "ABAAAAAAAAAAAAAAAAABA")
            .aisle("ABAAAAAAAAAAAAAAAAABA", "BDBAAAAAAAAAAAAAAABDB", "ABAAAAAAAAAAAAAAAAABA")
            .aisle("ABAAAAAAAAAAAAAAAAABA", "BDBAAAAAAAAAAAAAAABDB", "ABAAAAAAAAAAAAAAAAABA")
            .aisle("AABAAAAAAAAAAAAAAABAA", "ABDBAAAAAAAAAAAAABDBA", "AABAAAAAAAAAAAAAAABAA")
            .aisle("AABAAAAAAAAAAAAAAABAA", "ABDBAAAAAAAAAAAAABDBA", "AABAAAAAAAAAAAAAAABAA")
            .aisle("AAABAAAAAAAAAAAAABAAA", "AABDBAAAAAAAAAAABDBAA", "AAABAAAAAAAAAAAAABAAA")
            .aisle("AAAABAAAAAAAAAAABAAAA", "AAABDBBAAAAAAABBDBAAA", "AAAABAAAAAAAAAAABAAAA")
            .aisle("AAAAABBAAAAAAABBAAAAA", "AAAABDDBBBBBBBDDBAAAA", "AAAAABBAAAAAAABBAAAAA")
            .aisle("AAAAAAABBBBBBBAAAAAAA", "AAAAABBDDDDDDDBBAAAAA", "AAAAAAABBBBBBBAAAAAAA")
            .aisle("AAAAAAAAAAAAAAAAAAAAA", "AAAAAAABBBBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAAAA")
                .where("E", Predicates.controller(Predicates.blocks(definition.get())))
                .where("A", Predicates.any())
                .where("D", Predicates.blocks("kubejs:fusion_coil_block_mk_3"))
                .where("B", Predicates.blocks("kubejs:fusion_machine_casing_mk_v")
                    .setMinGlobalLimited(200)
                        .or(Predicates.abilities(
                            PartAbility.IMPORT_FLUIDS,
                            PartAbility.EXPORT_FLUIDS,
                            PartAbility.INPUT_ENERGY
                        ))
                        .or(Predicates.abilities(PartAbility.PARALLEL_HATCH)
                            .setMaxGlobalLimited(1)
                        )
            )
            .build()
        )
        .workableCasingModel("kubejs:block/fusion/fusion_machine_casing_mk_v", 'gtceu:block/multiblock/fusion_reactor')
})